"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {toast} from "sonner";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Textarea} from "@/components/ui/textarea";
import {RadioChips} from "@/components/ui/radio-chips";
import {formatDate} from "@/lib/utils";
import {amendmentLabels,amendmentTypes,scopeLabels} from "@/lib/finance/contract-labels";
import {procedureTypeLabel} from "@/lib/enums";
import {bindContractScope,draftAmendment,activateAmendment,cancelAmendment,type getFinanceLedger} from "@/server/finance/ledger-actions";
type Data=Awaited<ReturnType<typeof getFinanceLedger>>;
type Part={title:string;amount:string;dueState:"UNKNOWN"|"DATE_SET"|"CONDITIONAL";dueDate:string;dueCondition:string};
const date=(s:string)=>new Date(`${s}T00:00:00+08:00`),yuan=(s:string|null)=>`¥${Number(s??0).toLocaleString("zh-CN",{minimumFractionDigits:2})}`;
export function ContractWorkspace({data,canWrite,canCorrect}:{data:Data;canWrite:boolean;canCorrect:boolean}){
 const router=useRouter();const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[sourceId,setSourceId]=useState("");
 const [type,setType]=useState<typeof amendmentTypes[number]>("ADDITION"),[amount,setAmount]=useState(""),[title,setTitle]=useState("补充协议"),[reason,setReason]=useState("");
 const [signed,setSigned]=useState(formatDate(new Date())),[effective,setEffective]=useState(formatDate(new Date())),[ends,setEnds]=useState("");
 const [completed,setCompleted]=useState(""),[handover,setHandover]=useState(""),[docs,setDocs]=useState<string[]>([]),[parts,setParts]=useState<Part[]>([]);
 const [reductions,setReductions]=useState<Record<string,string>>({}),[reversals,setReversals]=useState<Record<string,string>>({});
 const [binding,setBinding]=useState<string|null>(null),[scopeProcedure,setScopeProcedure]=useState(""),[scopeNote,setScopeNote]=useState("");
 const [scopes,setScopes]=useState<Record<string,{state:"COVERED"|"SUPPLEMENT_REQUIRED"|"PENDING_REVIEW";note:string}>>({});
 const procedureName=(id:string)=>{const p=data.procedures.find(p=>p.id===id);return p?(p.customLabel??procedureTypeLabel[p.type]):"程序";};
 const byId=new Map(data.billings.map(b=>[b.id,b])), source=byId.get(sourceId);
 const lineage=new Set<string>();let cursor=source;while(cursor&&!lineage.has(cursor.id)){lineage.add(cursor.id);cursor=cursor.sourceBillingId?byId.get(cursor.sourceBillingId):undefined;}
 const ars=data.receivables.filter(r=>r.billingId&&lineage.has(r.billingId));
 const activeChildren=new Set(data.billings.filter(b=>b.status==='ACTIVE').map(b=>b.sourceBillingId));
 const eligible=data.billings.filter(b=>b.status==='ACTIVE'&&b.signedAt&&b.amendmentType!=="TERMINATION"&&!activeChildren.has(b.id)&&data.matters.find(m=>m.id===b.matterId)?.status!=="ARCHIVED");
 async function run(work:()=>Promise<{ok:boolean;message?:string}>,message:string){setBusy(true);try{const r=await work();if(!r.ok)throw new Error(r.message);toast.success(message);setOpen(false);router.refresh();}catch(e){toast.error(e instanceof Error?e.message:"保存失败");}finally{setBusy(false);}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!source)return;await run(()=>draftAmendment({sourceBillingId:source.id,sourceRevision:source.revision,title,type,amount,signedAt:date(signed),effectiveAt:date(effective),endsAt:ends?date(ends):undefined,reason,completedWork:completed,handoverWork:handover,documentIds:docs,scopes:Object.entries(scopes).map(([procedureId,s])=>({procedureId,...s})),installments:parts.map(p=>({...p,dueDate:p.dueState==='DATE_SET'?date(p.dueDate):undefined})),reductions:ars.filter(r=>reductions[r.id]?.trim()).map(r=>({receivableId:r.id,revision:r.revision,amount:reductions[r.id],allocationReversals:data.allocations.filter(a=>a.receivableId===r.id&&reversals[a.id]?.trim()).map(a=>({targetId:a.id,amount:reversals[a.id]}))}))}),"变更草稿已保存，请核对前后总额后确认生效");}
 function start(){setSourceId(eligible[0]?.id??"");setType("ADDITION");setAmount("");setTitle("补充协议");setReason("");setSigned(formatDate(new Date()));setEffective(formatDate(new Date()));setEnds("");setCompleted("");setHandover("");setDocs([]);setParts([]);setReductions({});setReversals({});setScopes({});setOpen(true);}
 return <section className="space-y-3 rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">合同版本与代理范围</h2>{canWrite&&<button className="btn btn-secondary btn-sm" disabled={!eligible.length} onClick={start}>新增补充协议</button>}</div><p className="text-sm text-muted-foreground">追加、调减与替代总价分别处理；每条合同链只计当前生效总额，原合同留存。</p>
 {data.billings.map(b=><article key={b.id} className="space-y-2 border-t pt-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{b.title} · {amendmentLabels[(b.amendmentType??'ORIGINAL') as keyof typeof amendmentLabels]}</strong><span>{b.status==='DRAFT'?'草稿':!b.signedAt?'已作废':activeChildren.has(b.id)?'历史版本':'当前生效版本'}</span></div><p>{b.sourceBillingId?`承接：${byId.get(b.sourceBillingId)?.title??'原版本'} · 变更前 ${yuan(b.previousAmount)} → 变更后 ${yuan(b.resultingAmount)}`:`合同额 ${yuan(b.contractAmount)}`}</p>{b.draftTerms&&<p>{b.draftTerms.reason} · 签署 {formatDate(b.draftTerms.signedAt as Date)} · 生效 {formatDate(b.draftTerms.effectiveAt as Date)}</p>}{data.contractDocuments.filter(d=>d.billingId===b.id).map(d=><a key={d.id} className="mr-3 underline" href={`/api/documents/${d.id}/download`} target="_blank" rel="noreferrer">{d.name}</a>)}{b.terminationReason&&<p>终止：{b.terminationReason} · 已完成：{b.completedWork} · 待交接：{b.handoverWork}</p>}{data.scopes.filter(s=>s.billingId===b.id).map(s=><p key={s.procedureId}>{procedureName(s.procedureId)} · {scopeLabels[s.state]} · {s.note}</p>)}{canWrite&&eligible.some(e=>e.id===b.id)&&<button className="btn btn-secondary btn-sm" onClick={()=>{setBinding(b.id);setScopeProcedure(data.procedures.find(p=>p.matterId===b.matterId)?.id??'');setScopeNote('');}}>确认既有合同覆盖范围</button>}{binding===b.id&&<form className="space-y-2 rounded border p-3" onSubmit={e=>{e.preventDefault();void run(()=>bindContractScope({billingId:b.id,revision:b.revision,procedureId:scopeProcedure,state:'COVERED',note:scopeNote}),'范围依据已保存，请重新完成冲突复核后开始办理').then(()=>setBinding(null));}}><select aria-label="覆盖的程序" className="w-full rounded border p-2" value={scopeProcedure} onChange={e=>setScopeProcedure(e.target.value)}>{data.procedures.filter(p=>p.matterId===b.matterId).map(p=><option key={p.id} value={p.id}>{procedureName(p.id)}</option>)}</select><Textarea required aria-label="合同条款或零收费豁免依据" value={scopeNote} onChange={e=>setScopeNote(e.target.value)} placeholder="合同条款或零收费豁免依据"/><button disabled={busy} className="btn btn-secondary btn-sm">保存覆盖依据</button></form>}{b.status==='DRAFT'&&b.sourceBillingId&&(canWrite||canCorrect)&&<button disabled={busy} className="btn btn-secondary btn-sm" onClick={()=>void run(()=>activateAmendment(b.id,b.revision),"合同变更及对应应收已同时生效")}>核对并确认生效</button>}{b.status==='DRAFT'&&b.sourceBillingId&&canWrite&&<button disabled={busy} className="btn btn-ghost btn-sm" onClick={()=>void run(()=>cancelAmendment(b.id,b.revision),"变更草稿已作废，原稿留存")}>作废草稿</button>}</article>)}
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="max-h-[88vh] overflow-y-auto"><DialogHeader><DialogTitle>新增补充协议</DialogTitle><DialogDescription>保存后先形成草稿，确认生效时复核余额。减少费用需要独立财务更正确认权限。</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4">
 <div><Label htmlFor="contract-source">当前合同版本</Label><select id="contract-source" required className="w-full rounded border bg-background p-2" value={sourceId} onChange={e=>{setSourceId(e.target.value);setDocs([]);setParts([]);setReductions({});setReversals({});setScopes({});}}>{eligible.map(b=><option key={b.id} value={b.id}>{b.title} · {data.matters.find(m=>m.id===b.matterId)?.title} · {yuan(b.resultingAmount??b.contractAmount)}</option>)}</select></div>
 <RadioChips value={type} items={amendmentTypes.map(value=>({value,label:amendmentLabels[value]}))} onChange={v=>setType(v as typeof type)}/>
 <div><Label htmlFor="contract-title">协议名称</Label><Input id="contract-title" required value={title} onChange={e=>setTitle(e.target.value)}/></div>
 <div><Label htmlFor="contract-amount">{type==='REPLACEMENT'||type==='TERMINATION'?'变更后总价':type==='SCOPE_ONLY'?'金额（仅范围变更填 0）':'本次追加或调减金额'}</Label><Input id="contract-amount" required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></div>
 <div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="contract-signed">签署日期</Label><Input id="contract-signed" required type="date" value={signed} onChange={e=>setSigned(e.target.value)}/></div><div><Label htmlFor="contract-effective">生效日期</Label><Input id="contract-effective" required type="date" value={effective} onChange={e=>setEffective(e.target.value)}/></div></div>
 <div><Label htmlFor="contract-ends">到期或终止日期</Label><Input id="contract-ends" type="date" required={type==='TERMINATION'} value={ends} onChange={e=>setEnds(e.target.value)}/></div>
 <div><Label htmlFor="contract-reason">变更原因、服务范围或零收费依据</Label><Textarea id="contract-reason" required value={reason} onChange={e=>setReason(e.target.value)}/></div>
 {type==='TERMINATION'&&<><div><Label htmlFor="contract-completed">已完成事项</Label><Textarea id="contract-completed" required value={completed} onChange={e=>setCompleted(e.target.value)}/></div><div><Label htmlFor="contract-handover">待交接事项（没有请填无）</Label><Textarea id="contract-handover" required value={handover} onChange={e=>setHandover(e.target.value)}/></div></>}
 <fieldset className="space-y-2"><legend>变更依据材料</legend>{data.documents.filter(d=>d.matterId===source?.matterId).map(d=><label className="flex gap-2 text-sm" key={d.id}><input type="checkbox" checked={docs.includes(d.id)} onChange={e=>setDocs(e.target.checked?[...docs,d.id]:docs.filter(id=>id!==d.id))}/>{d.name}</label>)}{!data.documents.some(d=>d.matterId===source?.matterId)&&<p className="text-sm text-muted-foreground">请本案经办先在案件材料中上传签署文件。</p>}</fieldset>
 <fieldset className="space-y-2 rounded border p-3"><legend>新增应收分期（仅费用增加时填写）</legend>{parts.map((p,i)=><div className="space-y-2 border-b pb-2" key={i}><Input aria-label={`新增第${i+1}期名称`} value={p.title} onChange={e=>setParts(parts.map((x,n)=>n===i?{...x,title:e.target.value}:x))}/><Input aria-label={`新增第${i+1}期金额`} value={p.amount} inputMode="decimal" onChange={e=>setParts(parts.map((x,n)=>n===i?{...x,amount:e.target.value}:x))}/><RadioChips value={p.dueState} items={[{value:'UNKNOWN',label:'未约定日期'},{value:'DATE_SET',label:'确定日期'},{value:'CONDITIONAL',label:'条件成就'}]} onChange={v=>setParts(parts.map((x,n)=>n===i?{...x,dueState:v as Part['dueState']}:x))}/>{p.dueState==='DATE_SET'&&<Input aria-label={`新增第${i+1}期到期日`} required type="date" value={p.dueDate} onChange={e=>setParts(parts.map((x,n)=>n===i?{...x,dueDate:e.target.value}:x))}/>} {p.dueState==='CONDITIONAL'&&<Input aria-label={`新增第${i+1}期条件`} required value={p.dueCondition} onChange={e=>setParts(parts.map((x,n)=>n===i?{...x,dueCondition:e.target.value}:x))}/>}<button type="button" className="text-sm text-destructive" onClick={()=>setParts(parts.filter((_,n)=>n!==i))}>移除此期</button></div>)}<button type="button" className="btn btn-secondary btn-sm" onClick={()=>setParts([...parts,{title:`追加第${parts.length+1}期`,amount:'',dueState:'UNKNOWN',dueDate:'',dueCondition:''}])}>添加新增分期</button></fieldset>
 <fieldset className="space-y-2 rounded border p-3"><legend>调减应收（仅费用减少时填写）</legend>{ars.map(r=><div className="space-y-2" key={r.id}><Label htmlFor={`reduce-${r.id}`}>{r.title} · 原额 {yuan(r.amount)} · 已核销 {yuan(r.settledAmount)}</Label><Input id={`reduce-${r.id}`} inputMode="decimal" placeholder="本期调减金额，不减少留空" value={reductions[r.id]??''} onChange={e=>setReductions({...reductions,[r.id]:e.target.value})}/>{data.allocations.filter(a=>a.receivableId===r.id&&Number(a.amount)>0).map(a=><div className="pl-3" key={a.id}><Label htmlFor={`release-${a.id}`}>解除核销（有效额 {yuan(a.amount)}）</Label><Input id={`release-${a.id}`} inputMode="decimal" value={reversals[a.id]??''} placeholder="仅填本次需要释放的金额" onChange={e=>setReversals({...reversals,[a.id]:e.target.value})}/></div>)}</div>)}</fieldset>
 <fieldset className="space-y-2"><legend>本次涉及程序</legend>{data.procedures.filter(p=>p.matterId===source?.matterId).map(p=><div key={p.id} className="space-y-2 rounded border p-3"><label className="flex gap-2"><input type="checkbox" checked={Boolean(scopes[p.id])} onChange={e=>{const next={...scopes};if(e.target.checked)next[p.id]={state:'PENDING_REVIEW',note:''};else delete next[p.id];setScopes(next);}}/>{p.customLabel??procedureTypeLabel[p.type]}</label>{scopes[p.id]&&<><RadioChips value={scopes[p.id].state} items={Object.entries(scopeLabels).map(([value,label])=>({value,label}))} onChange={v=>setScopes({...scopes,[p.id]:{...scopes[p.id],state:v as typeof scopes[string]['state']}})}/><Input aria-label={`${p.customLabel??procedureTypeLabel[p.type]}范围依据`} required placeholder="服务范围、豁免或待补充说明" value={scopes[p.id].note} onChange={e=>setScopes({...scopes,[p.id]:{...scopes[p.id],note:e.target.value}})}/></>}</div>)}</fieldset>
 <button className="btn btn-primary" disabled={busy} type="submit">{busy?'保存中…':'保存变更草稿'}</button></form></DialogContent></Dialog></section>;
}
