"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioChips } from "@/components/ui/radio-chips";
import { formatDate } from "@/lib/utils";
import { submitCorrection, decideCorrection, settleCommission, type getFinanceLedger } from "@/server/finance/ledger-actions";
import { actionErrorMessage } from "@/lib/action-error";
type Data = Awaited<ReturnType<typeof getFinanceLedger>>;
const types = { EXPENSE_REVERSAL:"支出误录冲销", REFUND:"退款", DISCOUNT:"应收折让", REVERSAL:"误录冲销" };
const states: Record<string,string> = { PENDING:"待确认", CONFIRMED:"已确认", REJECTED:"已退回", CANCELLED:"已撤销" };
const yuan = (n:string) => `¥${Number(n).toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function CorrectionWorkspace({data,canWrite,canCorrect,canSettle}:{data:Data;canWrite:boolean;canCorrect:boolean;canSettle:boolean}) {
  const router=useRouter();
  const [dialogOpen,setDialogOpen]=useState(false);
  const [mode,setMode]=useState<"request"|"decision"|"settle"|null>(null), [busy,setBusy]=useState(false);
  const [type,setType]=useState<keyof typeof types>("REFUND"), [targetId,setTarget]=useState(""), [amount,setAmount]=useState("");
  const [date,setDate]=useState(formatDate(new Date())), [reason,setReason]=useState(""), [voucher,setVoucher]=useState("");
  const [debt,setDebt]=useState<"KEEP_DEBT"|"WAIVE_DEBT">("KEEP_DEBT"), [alloc,setAlloc]=useState<Record<string,string>>({}), [invoice,setInvoice]=useState<Record<string,string>>({}), [waivers,setWaivers]=useState<Record<string,string>>({});
  const [decision,setDecision]=useState<"CONFIRMED"|"REJECTED"|"CANCELLED">("CONFIRMED"), [request,setRequest]=useState<Data["corrections"][number]|null>(null);
  const [commission,setCommission]=useState<Data["commissions"][number]|null>(null), [kind,setKind]=useState<"PAID"|"RECOVERED">("PAID");
  // 归档案件默认只读；本案指定的财务收尾人（tailWritable）仍可处理更正与分成结算
  const writable=(id:string)=>data.matters.find(m=>m.id===id)?.status!=="ARCHIVED"||data.matters.find(m=>m.id===id)?.tailWritable===true;
  const matter=(id:string)=>data.matters.find(m=>m.id===id)?.title??"案件";
  const arName=(id:string)=>data.receivables.find(r=>r.id===id)?.title??"应收";
  const paymentName=(id:string)=>{const p=data.payments.find(p=>p.id===id);return p?`${formatDate(p.occurredAt)} 收款 ${yuan(p.amount)} · ${matter(p.matterId)}`:"原收款";};
  const invoiceName=(id:string)=>data.invoices.find(i=>i.id===id)?.invoiceNo??"未填写票号";
  const target=type==="EXPENSE_REVERSAL"?data.expenses.find(e=>e.id===targetId):type==="DISCOUNT"?data.receivables.find(r=>r.id===targetId):data.payments.find(p=>p.id===targetId);
  const reset=()=>{setAmount("");setDate(formatDate(new Date()));setReason("");setVoucher("");setAlloc({});setInvoice({});setWaivers({});setDebt("KEEP_DEBT");};
  const rows=(values:Record<string,string>)=>Object.entries(values).filter(([,v])=>v.trim()).map(([targetId,amount])=>({targetId,amount}));
  async function submit(event:React.FormEvent) {
    event.preventDefault();setBusy(true);
    try {
      const result=mode==="request"&&target ? await submitCorrection({targetId,revision:target.revision,type:type==="EXPENSE_REVERSAL"?"REVERSAL":type,targetKind:type==="EXPENSE_REVERSAL"?"EXPENSE":"LEDGER",amount,occurredAt:new Date(`${date}T00:00:00+08:00`),reason,voucherReference:voucher,debtTreatment:debt,allocationReversals:rows(alloc),invoiceReversals:rows(invoice),waivers:rows(waivers)})
        : mode==="decision"&&request ? await decideCorrection({id:request.id,revision:request.revision,decision,note:reason})
        : mode==="settle"&&commission ? await settleCommission({commissionEntryId:commission.id,revision:commission.revision,kind,amount,occurredAt:new Date(`${date}T00:00:00+08:00`),voucherReference:voucher,note:reason}) : null;
      if(!result?.ok)throw new Error(result?.message??"请选择账务对象");
      toast.success(mode==="request"?"已提交，确认前不改变余额":"处理已保存");setDialogOpen(false);router.refresh();
    } catch(e) {toast.error(e instanceof Error ? actionErrorMessage(e) :"保存失败");}finally{setBusy(false);}
  }
  const amountFields=(title:string,items:{id:string;label:string;amount:string}[],values:Record<string,string>,change:(v:Record<string,string>)=>void)=><fieldset className="space-y-2 rounded-lg border p-3"><legend className="px-1 text-sm font-medium">{title}</legend>{items.map(i=><div key={i.id}><Label htmlFor={`${title}-${i.id}`}>{i.label} · 当前 {yuan(i.amount)}</Label><Input id={`${title}-${i.id}`} inputMode="decimal" placeholder="本次金额，不处理留空" value={values[i.id]??""} onChange={e=>change({...values,[i.id]:e.target.value})}/></div>)}{!items.length&&<p className="text-sm text-muted-foreground">暂无关联记录</p>}</fieldset>;
  return <>
    <section className="space-y-3 rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">退款与账务更正</h2>{canWrite&&<button className="btn btn-secondary btn-sm" onClick={()=>{reset();setType("REFUND");setTarget("");setMode("request");setDialogOpen(true);}}>申请更正</button>}</div><p className="text-sm text-muted-foreground">申请不改变余额，财务确认后生效。原收款与应收保留，更正逐项留痕。</p>
      {data.corrections.filter(c=>!c.sourceBillingId).map(c=><article key={c.id} className="space-y-2 border-t pt-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><span>{matter(c.matterId)} · {c.requestPayload.input.targetKind==="EXPENSE"?"支出冲销":types[c.type as keyof typeof types]} {yuan(c.amount)} · {states[c.status]}</span><span>{formatDate(c.occurredAt)} · 申请人 {c.name}</span></div><p>{c.reason} · 凭据：{c.relatedDocNo}</p><details><summary className="cursor-pointer text-primary">查看更正明细</summary><div className="space-y-1 py-2"><p>原对象：{c.requestPayload.input.targetKind==="EXPENSE"?"原支出":c.type==="DISCOUNT"?arName(c.targetId):paymentName(c.targetId)}</p>{c.type==="REFUND"&&<p>{c.requestPayload.input.debtTreatment==="WAIVE_DEBT"?"退款并免除等额应收":"退款后保留债权"}</p>}{c.requestPayload.input.allocationReversals?.map(r=><p key={r.targetId}>撤回核销：{arName(data.allocations.find(a=>a.id===r.targetId)?.receivableId??"")} {yuan(String(r.amount))}</p>)}{c.requestPayload.input.invoiceReversals?.map(r=><p key={r.targetId}>撤回票款：{invoiceName(data.invoiceLinks.find(a=>a.id===r.targetId)?.invoiceId??"")} {yuan(String(r.amount))}</p>)}{c.requestPayload.input.waivers?.map(r=><p key={r.targetId}>免除应收：{arName(r.targetId)} {yuan(String(r.amount))}</p>)}{c.resolutionNote&&<p>处理说明：{c.resolutionNote}</p>}</div></details>{c.status==="PENDING"&&writable(c.matterId)&&<div className="flex gap-2">{(canCorrect?["CONFIRMED","REJECTED"] as const:[]).map(d=><button key={d} className="btn btn-secondary btn-sm" onClick={()=>{setRequest(c);setDecision(d);setReason("");setMode("decision");setDialogOpen(true);}}>{d==="CONFIRMED"?"核对并确认":"退回"}</button>)}{canWrite&&c.createdById===data.currentUserId&&<button className="btn btn-ghost btn-sm" onClick={()=>{setRequest(c);setDecision("CANCELLED");setReason("");setMode("decision");setDialogOpen(true);}}>撤销申请</button>}</div>}</article>)}{!data.corrections.length&&<p className="text-sm text-muted-foreground">暂无更正申请</p>}
    </section>
    <section className="space-y-3 rounded-xl border bg-card p-4"><h2 className="font-semibold">分成计提与实际支付</h2><p className="text-sm text-muted-foreground">退款调整计提；实际支付和扣回另记凭据。待扣回不代表已经收回。</p>{data.commissions.map(c=><article key={c.id} className="space-y-2 border-t pt-3 text-sm"><p className="font-medium">{c.name??"未指定受益人"} · {matter(c.matterId)}</p><p>原计提 {yuan(c.amount)} · 更正 {yuan(c.adjustment)} · 有效计提 {yuan(c.accrued)}</p><p>已支付 {yuan(c.paid)} · 已扣回 {yuan(c.recovered)} · 待支付 {yuan(c.payable)} · 待扣回 {yuan(c.recoverable)}</p>{canSettle&&writable(c.matterId)&&<div className="flex gap-2">{(["PAID","RECOVERED"] as const).map(k=><button key={k} disabled={Number(k==="PAID"?c.payable:c.netPaid)<=0} className="btn btn-secondary btn-sm" onClick={()=>{reset();setCommission(c);setKind(k);setMode("settle");setDialogOpen(true);}}>{k==="PAID"?"登记支付":"登记扣回"}</button>)}</div>}<details><summary className="cursor-pointer text-primary">支付与扣回记录</summary>{data.settlements.filter(s=>s.commissionEntryId===c.id).map(s=><p key={s.id} className="py-1">{formatDate(s.occurredAt)} · {s.kind==="PAID"?"支付":"扣回"} {yuan(s.amount)} · {s.name} · {s.voucherReference}</p>)}</details></article>)}{!data.commissions.length&&<p className="text-sm text-muted-foreground">暂无分成计提</p>}</section>
    <Dialog open={dialogOpen} onOpenChange={open=>{if(!open&&!busy)setDialogOpen(false);}}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{mode==="request"?"申请账务更正":mode==="settle"?(kind==="PAID"?"登记实际分成支付":"登记实际分成扣回"):decision==="CONFIRMED"?"确认账务更正":decision==="REJECTED"?"退回更正申请":"撤销更正申请"}</DialogTitle><DialogDescription>{mode==="decision"?"请核对原对象、金额、关联撤回与债权处理；确认后立即改变账务余额。":"填写真实发生日期及凭据。所有金额与权限在保存时重新核对。"}</DialogDescription></DialogHeader>
      <form onSubmit={submit} className="space-y-4">
        {mode==="request"&&<><RadioChips value={type} items={Object.entries(types).map(([value,label])=>({value,label}))} onChange={v=>{setType(v as keyof typeof types);setTarget("");reset();}}/><div><Label htmlFor="correction-target">原账务对象</Label><select required id="correction-target" className="w-full rounded-md border bg-background p-2" value={targetId} onChange={e=>{setTarget(e.target.value);setAlloc({});setInvoice({});setWaivers({});}}><option value="">请选择</option>{type==="EXPENSE_REVERSAL"?data.expenses.filter(e=>writable(e.matterId)&&Number(e.reversed)===0).map(e=><option key={e.id} value={e.id}>{formatDate(e.occurredAt)} 支出 {yuan(e.amount)} · {matter(e.matterId)} · {e.note}</option>):type==="DISCOUNT"?data.receivables.filter(r=>writable(r.matterId)&&r.status!=="CANCELLED").map(r=><option key={r.id} value={r.id}>{r.title} · {matter(r.matterId)} · 原额 {yuan(r.amount)}</option>):data.payments.filter(p=>writable(p.matterId)).map(p=><option key={p.id} value={p.id}>{paymentName(p.id)} · 已更正 {yuan(p.refundedAmount)}</option>)}</select></div>{type==="REFUND"&&<RadioChips value={debt} items={[{value:"KEEP_DEBT",label:"退款后保留债权"},{value:"WAIVE_DEBT",label:"退款并免除等额应收"}]} onChange={v=>{setDebt(v as typeof debt);setWaivers({});}}/>}</>}
        {mode!=="decision"&&<><div><Label htmlFor="correction-amount">本次金额</Label><Input id="correction-amount" required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div><Label htmlFor="correction-date">实际发生日期</Label><Input id="correction-date" required type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div><Label htmlFor="correction-voucher">凭据编号或材料依据</Label><Input id="correction-voucher" required value={voucher} onChange={e=>setVoucher(e.target.value)}/></div></>}
        {mode==="request"&&target&&type!=="EXPENSE_REVERSAL"&&<>{amountFields("撤回核销",data.allocations.filter(a=>Number(a.amount)>0).filter(a=>type==="DISCOUNT"?a.receivableId===targetId:a.paymentId===targetId).map(a=>({id:a.id,label:type==="DISCOUNT"?paymentName(a.paymentId):arName(a.receivableId),amount:a.amount})),alloc,setAlloc)}{type!=="DISCOUNT"&&amountFields("撤回票款关联",data.invoiceLinks.filter(a=>Number(a.amount)>0).filter(a=>a.paymentId===targetId).map(a=>({id:a.id,label:invoiceName(a.invoiceId),amount:a.amount})),invoice,setInvoice)}{debt==="WAIVE_DEBT"&&amountFields("免除应收",data.receivables.filter(r=>r.matterId===target.matterId&&r.moneyKind===target.moneyKind&&r.status!=="CANCELLED").map(r=>({id:r.id,label:r.title,amount:r.amount})),waivers,setWaivers)}</>}
        {mode==="decision"&&request&&<div className="space-y-2 rounded-lg border p-3 text-sm"><p>{types[request.type as keyof typeof types]} {yuan(request.amount)} · {request.requestPayload.input.targetKind==="EXPENSE"?"原支出":request.type==="DISCOUNT"?arName(request.targetId):paymentName(request.targetId)}</p><p>{request.reason} · 凭据 {request.relatedDocNo}</p><p>{request.requestPayload.input.debtTreatment==="WAIVE_DEBT"?"同时免除等额债权":"保留其余债权"}</p>{request.requestPayload.input.allocationReversals?.map(r=><p key={r.targetId}>撤回核销 {arName(data.allocations.find(a=>a.id===r.targetId)?.receivableId??"")}：{yuan(String(r.amount))}</p>)}{request.requestPayload.input.invoiceReversals?.map(r=><p key={r.targetId}>撤回票款 {invoiceName(data.invoiceLinks.find(a=>a.id===r.targetId)?.invoiceId??"")}：{yuan(String(r.amount))}</p>)}{request.requestPayload.input.waivers?.map(r=><p key={r.targetId}>免除 {arName(r.targetId)}：{yuan(String(r.amount))}</p>)}</div>}
        <div><Label htmlFor="correction-reason">{mode==="request"?"更正原因":"处理说明"}</Label><Input id="correction-reason" required={mode==="request"||(mode==="decision"&&decision!=="CONFIRMED")} value={reason} onChange={e=>setReason(e.target.value)}/></div>
        <button type="submit" className="btn btn-primary" disabled={busy}>{busy?"保存中…":mode==="request"?"提交待确认":mode==="decision"&&decision==="CONFIRMED"?"确认并入账":"保存"}</button>
      </form>
    </DialogContent></Dialog>
  </>;
}
