'use client';
import {useState,useTransition} from 'react';import {useRouter} from 'next/navigation';import {toast} from 'sonner';import {adjustInvoice,type getFinanceLedger} from '@/server/finance/ledger-actions';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';import {Button} from '@/components/ui/button';import {shDayKey} from '@/lib/ui/sh-time';
type Data=Awaited<ReturnType<typeof getFinanceLedger>>;
export function InvoiceAdjustments({data,canCorrect}:{data:Data;canCorrect:boolean}){
 const router=useRouter(),[open,setOpen]=useState(false),[busy,start]=useTransition(),[id,setId]=useState(''),[kind,setKind]=useState<'RED'|'VOID'|'REPLACE'>('RED'),[amount,setAmount]=useState(''),[date,setDate]=useState(shDayKey(new Date())),[reference,setReference]=useState(''),[reason,setReason]=useState(''),[doc,setDoc]=useState(''),[replacement,setReplacement]=useState(''),[reversals,setReversals]=useState<Record<string,string>>({});
 const invoice=data.invoices.find(i=>i.id===id);
 return <section className="space-y-3 rounded-xl border p-4"><h2 className="font-semibold">已开票更正</h2><p className="text-sm">记录已完成的红冲、作废或换开，保留原票。不改变收款与应收；退款另行办理。</p>{canCorrect&&<Button variant="outline" onClick={()=>{const i=data.invoices.find(i=>Number(i.amount)>0);setId(i?.id??'');setAmount(i?.amount??'');setReversals({});setDoc('');setReplacement('');setReference('');setReason('');setOpen(true);}}>登记发票更正</Button>}{data.invoiceAdjustments.map(a=><p className="text-sm" key={a.id}>{{RED:'红冲',VOID:'作废',REPLACE:'换开'}[a.kind]??a.kind} ¥{a.amount} · {a.reference} · {a.reason} · <a className="underline" href={`/api/documents/${a.documentId}/download`}>处理依据</a></p>)}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>登记外部发票处理结果</DialogTitle><DialogDescription>须具备开票执行和财务更正确认权限。按实际外部凭证登记。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();start(async()=>{try{const r=await adjustInvoice({invoiceId:id,kind,amount,occurredAt:new Date(`${date}T00:00:00+08:00`),reference,reason,documentId:doc,replacementInvoiceId:kind==='REPLACE'?replacement:undefined,reversals:Object.entries(reversals).filter(([,amount])=>amount.trim()).map(([id,amount])=>({id,amount}))});if(!r.ok)throw new Error(r.message);toast.success('发票更正已留痕');setOpen(false);router.refresh();}catch(e){toast.error(e instanceof Error?e.message:'登记失败');}});}}>
 <label>原发票<select required className="block w-full rounded border p-2" value={id} onChange={e=>{setId(e.target.value);setReversals({});setDoc('');}}>{data.invoices.filter(i=>Number(i.amount)>0).map(i=><option key={i.id} value={i.id}>{i.invoiceNo??'未编号发票'} · 剩余票面 ¥{i.amount}</option>)}</select></label><label>处理类型<select className="block w-full rounded border p-2" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="RED">红冲</option><option value="VOID">作废</option><option value="REPLACE">换开</option></select></label><label>处理金额<Input required value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/></label><label>实际处理日期<Input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>外部凭证编号<Input required value={reference} onChange={e=>setReference(e.target.value)}/></label><label>处理说明<Textarea required value={reason} onChange={e=>setReason(e.target.value)}/></label><label>本案处理依据文件<select required className="block w-full rounded border p-2" value={doc} onChange={e=>setDoc(e.target.value)}><option value="">请先上传本案处理凭证，再选择</option>{data.documents.filter(d=>d.matterId===invoice?.matterId).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{kind==='REPLACE'&&<label>换开的新票<select required className="block w-full rounded border p-2" value={replacement} onChange={e=>setReplacement(e.target.value)}><option value="">请选择同案新票</option>{data.invoices.filter(i=>i.id!==id&&i.matterId===invoice?.matterId).map(i=><option key={i.id} value={i.id}>{i.invoiceNo} · ¥{i.amount}</option>)}</select></label>}{data.invoiceLinks.filter(l=>l.invoiceId===id&&Number(l.amount)>0).map(l=><label key={l.id} className="block">解除票款关联（当前 ¥{l.amount}）<Input inputMode="decimal" value={reversals[l.id]??''} onChange={e=>setReversals({...reversals,[l.id]:e.target.value})}/></label>)}<Button disabled={busy}>确认登记外部处理结果</Button></form></DialogContent></Dialog></section>;
}
