'use server';
import {intakeHandoverReady,requestIntakeHandoverTx,decideIntakeHandoverTx} from '@/server/intakes/handover';
import {Prisma} from '@prisma/client';import {z} from 'zod';import {revalidatePath} from 'next/cache';import {prisma} from '@/lib/prisma';import {requireSession} from '@/lib/auth/session';import {scopeFor,hasCustomPermission} from '@/lib/roles/catalog';import {matterAssociationFilter} from '@/lib/permissions';import {approvalTransaction} from '@/lib/approvals/service';
import {changeWorkTx,readWorkRows,responsibilityReady,workChangeInput,type WorkRow} from './responsibility';import {requestHandoverTx,decideHandoverTx,refreshHandoverTx,handoverInput} from '@/server/matters/handover';import {createUrgentTx,urgentInput,scanAdditionalWorkReminders} from './urgent';import {refreshScheduleReminderAfterSave} from './schedule';
export async function getWorkBoard(context?:{matterId?:string;intakeId?:string}){
 const session=await requireSession('personal');return prisma.$transaction(async db=>{
 if(!await responsibilityReady(db))return null;
 const emergency=scopeFor(session.user,'matters.transfer')==='ALL',canRead=hasCustomPermission(session.user,'schedule.read');
 const matters=!context?.intakeId&&(canRead||emergency)?await db.matter.findMany({where:{deletedAt:null,...(emergency?{}:matterAssociationFilter(session.user.id)),...(context?.matterId?{id:context.matterId}:{})},select:{id:true,title:true,ownerId:true,owner:{select:{name:true,active:true,role:true,roleDefinition:{select:{active:true,permissions:{select:{permissionKey:true}}}}}},status:true}}):[];
 const intakes=!context?.matterId&&(canRead||emergency)?await db.intake.findMany({where:{...(context?.intakeId?{id:context.intakeId}:{}),...(emergency?{status:{in:["INTAKE","NEEDS_REVISION","PENDING_CONFIRMATION"] as ("INTAKE"|"NEEDS_REVISION"|"PENDING_CONFIRMATION")[]}}:{OR:[{createdById:session.user.id},{ownerUserId:session.user.id},{coUserIds:{has:session.user.id}}]})},select:{id:true,title:true,ownerUserId:true,createdById:true,coUserIds:true,status:true,ownerUser:{select:{active:true,name:true}},createdBy:{select:{active:true,name:true}}}}):[];
 const ids=new Set(matters.map(m=>m.id)),iids=new Set(intakes.map(i=>i.id));
 const items=(await readWorkRows(db)).filter(w=>(!context?.matterId||w.matterId===context.matterId)&&(!context?.intakeId||w.intakeId===context.intakeId)&&(canRead&&(w.assigneeId===session.user.id||w.proposedAssigneeId===session.user.id||Boolean(w.matterId&&ids.has(w.matterId))||Boolean(w.intakeId&&iids.has(w.intakeId)))||emergency&&!w.active));
 const handovers=context?.intakeId?[]:await db.$queryRaw<{id:string;matterId:string;title:string;fromName:string;toName:string;fromUserId:string;toUserId:string;initiatedById:string;status:string;reason:string;emergency:boolean;revision:number;createdAt:Date;snapshot:{work:WorkRow[];procedures:{id:string;customLabel:string|null}[];pendingReceipts:{id:string}[];invoices:{id:string}[];seals:{id:string}[]}}[]>(Prisma.sql`SELECT h.*,m.title,u.name AS "fromName",v.name AS "toName" FROM "MatterHandover" h JOIN "Matter" m ON m.id=h."matterId" JOIN "User" u ON u.id=h."fromUserId" JOIN "User" v ON v.id=h."toUserId" WHERE (h."fromUserId"=${session.user.id} OR h."toUserId"=${session.user.id} OR h."initiatedById"=${session.user.id} OR ${emergency}::boolean) ${context?.matterId?Prisma.sql`AND h."matterId"=${context.matterId}`:Prisma.empty} ORDER BY h."createdAt" DESC`);
 const intakeHandovers=!context?.matterId&&await intakeHandoverReady(db)?await db.$queryRaw<{id:string;intakeId:string;title:string;fromName:string;toName:string;initiatedById:string;toUserId:string;status:string;emergency:boolean;reason:string;revision:number;snapshot:{urgent:{id:string;title:string;dueAt:Date}[]}}[]>(Prisma.sql`SELECT h.*,i.title,u.name AS "fromName",v.name AS "toName" FROM "IntakeHandover" h JOIN "Intake" i ON i.id=h."intakeId" JOIN "User" u ON u.id=h."fromUserId" JOIN "User" v ON v.id=h."toUserId" WHERE (h."fromUserId"=${session.user.id} OR h."toUserId"=${session.user.id} OR h."initiatedById"=${session.user.id} OR ${emergency}::boolean) ${context?.intakeId?Prisma.sql`AND h."intakeId"=${context.intakeId}`:Prisma.empty} ORDER BY h."createdAt" DESC`):[];
 const people=await db.user.findMany({where:{active:true,OR:[{role:{not:'CUSTOM'}},{role:'CUSTOM',roleDefinition:{active:true,permissions:{some:{permissionKey:'matters.write'}}}}]},select:{id:true,name:true}});
 return {currentUserId:session.user.id,emergency,canWrite:hasCustomPermission(session.user,'schedule.write'),canTransfer:hasCustomPermission(session.user,'matters.write'),items,handovers,intakeHandovers,people,matters:matters.map(m=>({...m,ownerInactive:!m.owner.active||(m.owner.role==='CUSTOM'&&(!m.owner.roleDefinition?.active||!m.owner.roleDefinition.permissions.some(p=>p.permissionKey==='matters.write')))})),intakes};
 },{isolationLevel:'RepeatableRead'});
}
async function refreshMatterWork(matterId:string){for(const w of (await readWorkRows(prisma)).filter(w=>w.matterId===matterId&&w.state==='OPEN'))if(w.kind==='Deadline'||w.kind==='Hearing')await refreshScheduleReminderAfterSave(w.kind,w.targetId);await scanAdditionalWorkReminders(prisma);}
async function done(){revalidatePath('/schedule');revalidatePath('/matters');revalidatePath('/intakes');revalidatePath('/matters/[id]','page');revalidatePath('/intakes/[id]','page');}
export async function changeWork(input:z.input<typeof workChangeInput>){const s=await requireSession('schedule.write');const row=await approvalTransaction(db=>changeWorkTx(db,s.user.id,input));if(row.kind==='Hearing'||row.kind==='Deadline')await refreshScheduleReminderAfterSave(row.kind,row.targetId);await scanAdditionalWorkReminders(prisma);await done();return {ok:true};}
export async function requestHandover(input:z.input<typeof handoverInput>){const s=await requireSession('personal');const r=await approvalTransaction(db=>requestHandoverTx(db,s.user.id,input));await refreshMatterWork(r.matterId);await done();return {ok:true};}
export async function decideHandover(input:{id:string;revision:number;decision:'ACCEPTED'|'CANCELLED';reason:string}){const s=await requireSession('personal');const d=z.object({id:z.string().min(1),revision:z.number().int().nonnegative(),decision:z.enum(['ACCEPTED','CANCELLED']),reason:z.string().max(2000)}).parse(input);const r=await approvalTransaction(db=>decideHandoverTx(db,s.user.id,d.id,d.revision,d.decision,d.reason));await refreshMatterWork(r.matterId);await done();return {ok:true};}
export async function refreshHandover(id:string,revision:number){const s=await requireSession('personal');await approvalTransaction(db=>refreshHandoverTx(db,s.user.id,id,revision));await done();return {ok:true};}
export async function createUrgent(input:z.input<typeof urgentInput>){const s=await requireSession('schedule.write');await approvalTransaction(db=>createUrgentTx(db,s.user.id,input));await scanAdditionalWorkReminders(prisma);await done();return {ok:true};}

export async function requestIntakeHandover(input:Parameters<typeof requestIntakeHandoverTx>[2]){const s=await requireSession('personal');await approvalTransaction(db=>requestIntakeHandoverTx(db,s.user.id,input));await scanAdditionalWorkReminders(prisma);await done();return {ok:true};}
export async function decideIntakeHandover(input:{id:string;revision:number;decision:'ACCEPT'|'CANCEL'|'REFRESH';reason:string}){const d=z.object({id:z.string().min(1),revision:z.number().int().nonnegative(),decision:z.enum(['ACCEPT','CANCEL','REFRESH']),reason:z.string().max(1500)}).parse(input),s=await requireSession('personal');await approvalTransaction(db=>decideIntakeHandoverTx(db,s.user.id,d.id,d.revision,d.decision,d.reason));await scanAdditionalWorkReminders(prisma);await done();return {ok:true};}
