"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Plus, Copy } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { BUILTIN_ROLES, ADMINISTRATIVE_ROLE_ID, PERMISSIONS, SCOPE_LABELS, copyBuiltinGrants, type RoleScope, type BuiltinRolePresentation } from "@/lib/roles/catalog";
import { saveRoleDefinition, saveBuiltinRolePresentation, type listRoleDefinitions } from "@/server/roles/actions";
import type { RoleDefinitionInput } from "@/server/roles/schema";
import { AdminPageHeader } from "@/components/layout/admin-page-header";
type Role = Awaited<ReturnType<typeof listRoleDefinitions>>["roles"][number];
const empty = (): RoleDefinitionInput => ({ name: "", description: "", active: true, permissions: [] });
export function RolesView({ roles, builtins = BUILTIN_ROLES.map(role => ({ ...role, version: 0 })) }: { roles: Role[]; builtins?: BuiltinRolePresentation[] }) {
  const router = useRouter();
  const [editing, setEditing] = useState<RoleDefinitionInput | null>(null);
  const [builtinEditing, setBuiltinEditing] = useState<BuiltinRolePresentation | null>(null);
  const [pending, start] = useTransition();
  const current = roles.find(r => r.id === editing?.id);
  const before = new Map(current?.permissions.map(p => [p.permissionKey, p.scope]) ?? []);
  const changes = editing ? PERMISSIONS.filter(p => before.get(p.key) !== editing.permissions.find(r => r.permissionKey === p.key)?.scope) : [];
  function save() {
    if (!editing) return;
    start(async () => { try { await saveRoleDefinition(editing); toast.success("角色已保存，权限变更立即生效"); setEditing(null); router.refresh(); } catch (e) { toast.error(e instanceof Error ? e.message : "保存失败"); } });
  }
  return <div className="space-y-5">
    <AdminPageHeader title="岗位角色" sub="配置岗位功能与数据范围，再到用户管理分配。审批及盖章回填在审批权限中单独授权。" actions={<Button size="sm" onClick={() => setEditing(empty())}><Plus />新增角色</Button>} />
    <div className="grid gap-3 sm:grid-cols-2">{roles.filter(role => role.id !== ADMINISTRATIVE_ROLE_ID).map(role => <article key={role.id} className="rounded-xl border bg-card p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{role.name}<span className="ml-2 text-xs font-normal text-muted-foreground">{role.active ? "已启用" : "已停用"}</span></h3><p className="mt-1 text-xs text-muted-foreground">自定义角色 · {role._count.users} 人使用</p></div><Button variant="outline" size="sm" onClick={() => setEditing({ id: role.id, version: role.version, name: role.name, description: role.description, active: role.active, permissions: role.permissions.map(p => ({ permissionKey: p.permissionKey, scope: p.scope as RoleScope })) })}>编辑</Button></div><p className="mt-3 text-sm text-muted-foreground">{role.description || "暂无职责说明"}</p><p className="mt-2 text-xs leading-6 text-muted-foreground">{role.permissions.map(p => `${PERMISSIONS.find(d => d.key === p.permissionKey)?.label ?? "未知权限"}（${SCOPE_LABELS[p.scope as RoleScope] ?? "未知范围"}）`).join("、") || "仅个人基础功能；审批按独立授权"}</p></article>)}</div>
    <section className="space-y-2"><h3 className="text-sm font-semibold">系统内置角色</h3><p className="text-xs text-muted-foreground">名称和介绍可修改，权限固定。复制可创建一份权限可调整的自定义角色。</p>{builtins.map(role => <article key={role.id} className="flex flex-wrap items-center justify-between gap-4 rounded-lg border bg-card p-4"><div className="min-w-0 flex-1"><h4 className="text-sm font-medium">{role.name}<span className="ml-2 text-xs font-normal text-muted-foreground">内置角色</span></h4><p className="mt-1 whitespace-pre-wrap break-words text-xs text-muted-foreground">{role.description || "暂无介绍"}</p></div><div className="flex shrink-0 gap-2"><Button size="sm" variant="outline" aria-label={`编辑${role.name}的名称和介绍`} onClick={() => setBuiltinEditing(role)}>编辑资料</Button><Button size="sm" variant="ghost" onClick={() => setEditing({ ...empty(), description: `参考${role.name}，请核对功能与范围`, permissions: role.id === ADMINISTRATIVE_ROLE_ID ? (roles.find(row => row.id === role.id)?.permissions ?? []).map(grant => ({ permissionKey: grant.permissionKey, scope: grant.scope as RoleScope })) : copyBuiltinGrants(role.id) })}><Copy className="mr-1 h-3.5 w-3.5" />复制新建</Button></div></article>)}</section>
    <Dialog open={Boolean(builtinEditing)} onOpenChange={open => { if (!open && !pending) setBuiltinEditing(null); }}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>编辑内置角色资料</DialogTitle><DialogDescription>修改显示名称和介绍，权限与人员分配保持原样。</DialogDescription></DialogHeader>{builtinEditing && <form className="space-y-4" onSubmit={event => {
      event.preventDefault();
      start(async () => { try { await saveBuiltinRolePresentation(builtinEditing); toast.success("角色资料已保存"); setBuiltinEditing(null); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "保存失败"); } });
    }}><label className="block space-y-2 text-sm">角色名称<Input required maxLength={60} value={builtinEditing.name} onChange={event => setBuiltinEditing({ ...builtinEditing, name: event.target.value })} /></label><label className="block space-y-2 text-sm">角色介绍<Textarea maxLength={300} value={builtinEditing.description} onChange={event => setBuiltinEditing({ ...builtinEditing, description: event.target.value })} /></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={pending} onClick={() => setBuiltinEditing(null)}>取消</Button><Button type="submit" disabled={pending}>{pending ? "保存中…" : "保存资料"}</Button></div></form>}</DialogContent></Dialog>
    <Dialog open={Boolean(editing)} onOpenChange={open => { if (!open && !pending) setEditing(null); }}><DialogContent className="max-h-[88dvh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{editing?.id ? "编辑角色" : "新增角色"}</DialogTitle><DialogDescription>勾选后选择数据范围。查看权限不会自动开放办理、材料下载或导出。完整案件导出还须具备案件查看、财务查看和材料下载权限；归档导出须具备案件及归档查看、材料下载权限。</DialogDescription></DialogHeader>{editing && <form className="space-y-5" onSubmit={e => { e.preventDefault(); save(); }}><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm">角色名称<Input required maxLength={60} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} placeholder="例如：档案管理员" /></label><label className="space-y-2 text-sm">职责说明<Textarea maxLength={300} value={editing.description} onChange={e => setEditing({ ...editing, description: e.target.value })} /></label></div>
      {[...new Set(PERMISSIONS.map(p => p.group))].map(group => <fieldset key={group} className="space-y-3 rounded-xl border p-4"><legend className="px-1 text-sm font-semibold">{group}</legend>{PERMISSIONS.filter(p => p.group === group).map(p => { const grant = editing.permissions.find(g => g.permissionKey === p.key); return <div key={p.key} className="flex flex-wrap items-center justify-between gap-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(grant)} onChange={e => setEditing({ ...editing, permissions: e.target.checked ? [...editing.permissions, { permissionKey: p.key, scope: p.scopes[0] }] : editing.permissions.filter(g => g.permissionKey !== p.key) })} />{p.label}</label>{grant && <select aria-label={`${p.label}的数据范围`} className="h-8 max-w-full rounded-md border bg-background px-2 text-xs" value={grant.scope} onChange={e => setEditing({ ...editing, permissions: editing.permissions.map(g => g.permissionKey === p.key ? { ...g, scope: e.target.value as RoleScope } : g) })}>{p.scopes.map(scope => <option key={scope} value={scope}>{SCOPE_LABELS[scope]}</option>)}</select>}</div>; })}</fieldset>)}
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.active} onChange={e => setEditing({ ...editing, active: e.target.checked })} />启用此角色</label>
      <div className="rounded-lg bg-muted p-3 text-sm"><p>影响账号：{current?._count.users ?? 0} 人。保存后相关账号需重新登录。</p>{!editing.active && <p className="mt-2">停用后，所属账号暂停业务访问及审批资格，请为这些人员重新分配角色。</p>}{changes.length > 0 && <ul className="mt-2 space-y-1 text-xs text-muted-foreground">{changes.map(p => { const after = editing.permissions.find(g => g.permissionKey === p.key)?.scope; return <li key={p.key}>{p.label}：{before.get(p.key) ? SCOPE_LABELS[before.get(p.key) as RoleScope] : "未授权"} → {after ? SCOPE_LABELS[after] : "撤销"}</li>; })}</ul>}</div>
      <div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={pending} onClick={() => setEditing(null)}>取消</Button><Button type="submit" disabled={pending}>{pending ? "保存中…" : "保存角色"}</Button></div>
    </form>}</DialogContent></Dialog>
  </div>;
}
