'use client';
import {useEffect,useState,useTransition} from 'react';import {toast} from 'sonner';import {getTermination,requestTermination,decideTermination} from '@/server/approval-permissions/termination-actions';import {Button} from '@/components/ui/button';import {Textarea} from '@/components/ui/textarea';import {formatDateTime} from '@/lib/utils';
import { actionErrorMessage } from "@/lib/action-error";
export function ExecutionTerminationPanel({kind,id,onChanged}:{kind:'INVOICE'|'SEAL';id:string;onChanged:()=>void}){
 const [data,setData]=useState<Awaited<ReturnType<typeof getTermination>>>(null),[note,setNote]=useState(''),[busy,start]=useTransition();
 useEffect(()=>{let alive=true;getTermination(kind,id).then(d=>{if(alive)setData(d);}).catch(e=>toast.error(e instanceof Error ? actionErrorMessage(e) :'无法读取终止记录'));return()=>{alive=false;};},[kind,id]);
 if(!data)return null;const pending=data.rows.find(r=>r.status==='PENDING');
 function act(decision?:'CONFIRMED'|'REJECTED'|'CANCELLED'){start(async()=>{try{if(decision&&pending)await decideTermination({id:pending.id,revision:pending.revision,decision,note});else await requestTermination(kind,id,note);setData(await getTermination(kind,id));setNote('');onChanged();toast.success('执行终止记录已更新');}catch(e){toast.error(e instanceof Error ? actionErrorMessage(e) :'处理失败');}});}
 if(!data.rows.length&&!data.canRequest)return null;
 return <div className="my-3 space-y-2 rounded-lg border p-3 text-sm"><p className="font-semibold">执行终止</p><p>原批准记录保留。待核实期间暂停执行，已经开票或盖章不能改为未执行。</p>{data.rows.map(r=><p key={r.id}>{formatDateTime(r.createdAt)} · {{PENDING:'待核实',CONFIRMED:'已终止',REJECTED:'不予终止',CANCELLED:'已撤回'}[r.status]??r.status} · {r.reason}{r.decisionNote&&`；核实：${r.decisionNote}`}</p>)}{(data.canRequest||data.canDecide||data.canCancel)&&<Textarea aria-label="终止或核实原因" value={note} onChange={e=>setNote(e.target.value)} placeholder="终止或核实原因"/>}<div className="flex flex-wrap gap-2">{data.canRequest&&<Button variant="outline" disabled={busy} onClick={()=>act()}>申请终止执行</Button>}{data.canDecide&&<><Button variant="outline" disabled={busy} onClick={()=>act('CONFIRMED')}>确认未执行并终止</Button><Button variant="outline" disabled={busy} onClick={()=>act('REJECTED')}>不予终止</Button></>}{data.soleResolver&&<p className="w-full text-xs text-amber-700">本所当前没有其他具备核实资格的人员，您可作为唯一持权人自核确认（审计留痕）。</p>}{data.canCancel&&<Button variant="outline" disabled={busy} onClick={()=>act('CANCELLED')}>撤回终止申请</Button>}</div></div>;
}
