'use client';
import {useState,useTransition} from 'react';import {useRouter} from 'next/navigation';import {toast} from 'sonner';import {getWorkBoard,requestIntakeHandover,decideIntakeHandover} from '@/server/reminders/work-actions';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {Button} from '@/components/ui/button';import {Textarea} from '@/components/ui/textarea';import {formatDateTime} from '@/lib/utils';
type Data=NonNullable<Awaited<ReturnType<typeof getWorkBoard>>>;
export function IntakeHandoverPanel({data,intakeId}:{data:Data;intakeId?:string}){
 const router=useRouter(),[open,setOpen]=useState(false),[busy,start]=useTransition(),[id,setId]=useState(intakeId??''),[person,setPerson]=useState(''),[reason,setReason]=useState(''),[emergency,setEmergency]=useState(false);
 const eligible=data.intakes.filter(i=>['INTAKE','NEEDS_REVISION','PENDING_CONFIRMATION'].includes(i.status)&&((i.ownerUserId??i.createdById)===data.currentUserId||data.emergency));
 async function run(fn:()=>Promise<unknown>){start(async()=>{try{await fn();setOpen(false);router.refresh();toast.success('收案交接已保存');}catch(e){toast.error(e instanceof Error?e.message:'交接失败');}});}
 return <div className="space-y-2">{eligible.length>0&&<Button variant="outline" onClick={()=>{const i=eligible.find(i=>i.id===intakeId)??eligible[0];setId(i.id);setEmergency((i.ownerUserId??i.createdById)!==data.currentUserId);setReason('');setPerson('');setOpen(true);}}>办理收案主办交接</Button>}{eligible.filter(i=>!(i.ownerUser??i.createdBy).active).map(i=><p key={i.id} className="text-sm text-red-700">{i.title}：主办已停用，须应急接管。</p>)}
 {data.intakeHandovers.filter(h=>!intakeId||h.intakeId===intakeId).map(h=>{const urgent=Array.isArray(h.snapshot?.urgent)?h.snapshot.urgent:[];return <article key={h.id} className="space-y-2 rounded border p-3 text-sm"><b>{h.title} · {h.fromName} → {h.toName}</b><p>{h.emergency?'应急接管已生效':'接收前由原主办负责'} · {h.status==='PENDING'?'待接收':h.status==='ACCEPTED'?'已接收':'已退回'} · {h.reason}</p>{h.snapshot?.urgent===undefined?<p className="text-muted-foreground">固定交接清单：快照未记录</p>:urgent.map(w=><p key={w.id}>{w.title} · {formatDateTime(w.dueAt)}</p>)}{h.status==='PENDING'&&<div className="flex gap-2">{h.toUserId===data.currentUserId&&<Button variant="outline" disabled={busy} onClick={()=>void run(()=>decideIntakeHandover({id:h.id,revision:h.revision,decision:'ACCEPT',reason:'已核对收案及紧急事项'}))}>核对并承接</Button>}{(h.initiatedById===data.currentUserId||data.emergency&&h.emergency)&&<Button variant="outline" disabled={busy} onClick={()=>void run(()=>decideIntakeHandover({id:h.id,revision:h.revision,decision:'REFRESH',reason:'重新核对当前清单'}))}>刷新清单</Button>}{!h.emergency&&[h.toUserId,h.initiatedById].includes(data.currentUserId)&&<Button variant="outline" disabled={busy} onClick={()=>void run(()=>decideIntakeHandover({id:h.id,revision:h.revision,decision:'CANCEL',reason:'退回发起人重新安排交接'}))}>退回重新安排</Button>}</div>}</article>;})}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>收案主办交接</DialogTitle><DialogDescription>原登记人和已送审轮次保留；待审批收案将在主办变更后重新送审。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();void run(()=>requestIntakeHandover({intakeId:id,toUserId:person,emergency,reason}));}}><label>收案<select className="block w-full rounded border p-2" value={id} onChange={e=>setId(e.target.value)}>{eligible.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label><label>接收人<select required className="block w-full rounded border p-2" value={person} onChange={e=>setPerson(e.target.value)}><option value="">请选择</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{data.emergency&&<label><input type="checkbox" checked={emergency} onChange={e=>setEmergency(e.target.checked)}/>应急接管，立即明确新主办</label>}<Textarea required aria-label="交接依据" placeholder="交接依据" value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={busy}>发起交接</Button></form></DialogContent></Dialog></div>;
}
