'use client';
import {IntakeHandoverPanel} from './intake-handover-panel';
import {useState} from 'react';import {useRouter} from 'next/navigation';import {toast} from 'sonner';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';import {Label} from '@/components/ui/label';import {formatDateTime} from '@/lib/utils';
import {getWorkBoard,changeWork,requestHandover,decideHandover,refreshHandover,createUrgent} from '@/server/reminders/work-actions';
import {completeTasksBatch} from '@/server/tasks/actions';
import {shDayKey,shTime} from '@/lib/ui/sh-time';
type Data=NonNullable<Awaited<ReturnType<typeof getWorkBoard>>>;type Item=Data['items'][number];
const kinds={Task:'任务',Deadline:'期限',Hearing:'开庭',Urgent:'收案紧急事项'},states={OPEN:'办理中',DONE:'已办结',CANCELLED:'已取消'};
const localDate=(d:Date|string)=>`${shDayKey(d)}T${shTime(d)}`;
export function WorkResponsibilityPanel({data,matterId,intakeId}:{data:Data|null;matterId?:string;intakeId?:string}){
 const router=useRouter(),[busy,setBusy]=useState(false),[mode,setMode]=useState<'work'|'handover'|'urgent'|null>(null),[item,setItem]=useState<Item|null>(null),[action,setAction]=useState<'PROPOSE'|'RESCHEDULE'|'COMPLETE'|'CANCEL'|'REOPEN'>('RESCHEDULE'),[reason,setReason]=useState(''),[person,setPerson]=useState(''),[date,setDate]=useState(localDate(new Date())),[selectedMatter,setMatter]=useState(matterId??''),[emergency,setEmergency]=useState(false),[title,setTitle]=useState(''),[kind,setKind]=useState<'TASK'|'DEADLINE'|'HEARING'>('DEADLINE'),[history,setHistory]=useState(false),[checked,setChecked]=useState<Record<string,boolean>>({}),[batchOpen,setBatchOpen]=useState(false),[batchReason,setBatchReason]=useState('');
 if(!data)return null;const d=data;
 const eligible=d.matters.filter(m=>m.status!=='ARCHIVED'&&(m.ownerId===d.currentUserId||d.emergency));
 // 历史快照可能缺字段（旧形状/占位数据）：缺失按空处理并标「快照未记录」，不得补造也不得崩页
 const snapOf=(h:Data['handovers'][number])=>({work:Array.isArray(h.snapshot?.work)?h.snapshot.work:[],procedures:Array.isArray(h.snapshot?.procedures)?h.snapshot.procedures:[],pendingReceipts:Array.isArray(h.snapshot?.pendingReceipts)?h.snapshot.pendingReceipts:[],invoices:Array.isArray(h.snapshot?.invoices)?h.snapshot.invoices:[],seals:Array.isArray(h.snapshot?.seals)?h.snapshot.seals:[],recorded:Array.isArray(h.snapshot?.work)&&Array.isArray(h.snapshot?.procedures)});
 async function run(work:()=>Promise<unknown>){setBusy(true);try{await work();setMode(null);router.refresh();toast.success('处理结果已保存');}catch(e){toast.error(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
 function openWork(i:Item,a:typeof action){setItem(i);setAction(a);setReason('');setPerson('');setDate(localDate(i.dueAt??new Date()));setMode('work');}
 function startHandover(id?:string){const m=eligible.find(m=>m.id===id)??eligible[0];setMatter(m?.id??'');setPerson('');setReason('');setEmergency(m?.ownerId!==d.currentUserId);setMode('handover');}
 async function submit(e:React.FormEvent){e.preventDefault();if(mode==='work'&&item)await run(()=>changeWork({id:item.id,revision:item.revision,action,reason,assigneeId:person||undefined,dueAt:action==='RESCHEDULE'?new Date(`${date}:00+08:00`):undefined}));else if(mode==='handover')await run(()=>requestHandover({matterId:selectedMatter,toUserId:person,emergency,reason}));else if(mode==='urgent'&&intakeId)await run(()=>createUrgent({intakeId,title,kind,assigneeId:person,dueAt:new Date(`${date}:00+08:00`),basis:reason}));}
 const items=d.items.filter(i=>history||i.state==='OPEN').sort((a,b)=>(a.dueAt?new Date(a.dueAt).getTime():Infinity)-(b.dueAt?new Date(b.dueAt).getTime():Infinity));
 return <section className="space-y-3 rounded-xl border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">事项责任与交接</h2><div className="flex gap-2">{intakeId&&d.canWrite&&<button className="btn btn-secondary btn-sm" onClick={()=>{setTitle('');setReason('');setPerson(d.currentUserId);setDate(localDate(new Date()));setMode('urgent');}}>登记紧急事项</button>}{!intakeId&&eligible.length>0&&(d.canTransfer||d.emergency)&&<button className="btn btn-secondary btn-sm" onClick={()=>startHandover(matterId)}>办理主办交接</button>}</div></div>
 {!matterId&&<IntakeHandoverPanel data={data} intakeId={intakeId}/>}
 {d.matters.filter(m=>m.ownerInactive&&m.status!=='ARCHIVED').map(m=><p key={m.id} className="rounded border border-red-300 bg-red-50 p-3 text-sm">{m.title}：原主办已停用，责任待交接。{d.emergency&&<button className="ml-2 underline" onClick={()=>startHandover(m.id)}>应急接管</button>}</p>)}
 {!intakeId&&d.handovers.map(h=>{const snap=snapOf(h);return <article key={h.id} className="space-y-2 rounded border p-3 text-sm"><b>{h.title} · {h.fromName} → {h.toName} · {h.status==='PENDING'?'待承接':h.status==='ACCEPTED'?'已承接':'已退回'}</b><p>{h.status==='ACCEPTED'?'接收人已核对并承接。':h.status==='CANCELLED'?'交接已取消，原责任不变。':h.emergency?'应急接管已生效，待接收人确认。':'接收前仍由原主办负责。'}{h.reason}</p><details><summary className="cursor-pointer">{snap.recorded?`固定交接清单：${snap.work.length} 项待办，${snap.procedures.length} 个未结程序`:'固定交接清单：快照未记录'}</summary>{snap.work.map(w=><p key={w.id}>{kinds[w.kind]}：{w.title} · {w.dueAt?formatDateTime(w.dueAt):'无截止日'} · 原责任人 {w.name}</p>)}<p>待确认实收 {snap.pendingReceipts.length} 笔，待处理开票 {snap.invoices.length} 项，用章 {snap.seals.length} 项。审批及财务执行仍须独立授权。</p></details>{h.status==='PENDING'&&<div className="flex flex-wrap gap-2">{h.toUserId===d.currentUserId&&<button disabled={busy} className="btn btn-primary btn-sm" onClick={()=>void run(()=>decideHandover({id:h.id,revision:h.revision,decision:'ACCEPTED',reason:'已核对并承接固定交接清单'}))}>核对并承接</button>}{h.initiatedById===d.currentUserId&&<button disabled={busy} className="btn btn-secondary btn-sm" onClick={()=>void run(()=>refreshHandover(h.id,h.revision))}>刷新交接清单</button>}{!h.emergency&&(h.initiatedById===d.currentUserId||h.toUserId===d.currentUserId)&&<button disabled={busy} className="btn btn-ghost btn-sm" onClick={()=>void run(()=>decideHandover({id:h.id,revision:h.revision,decision:'CANCELLED',reason:'当前交接清单不再适用，退回重新安排'}))}>退回重新安排</button>}</div>}</article>;})}
 <label className="flex gap-2 text-sm"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/>显示已办结和已取消事项</label>
 {items.map(i=><article key={i.id} className="space-y-2 border-t pt-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{i.kind==='Task'&&i.state==='OPEN'&&d.canWrite?<input type="checkbox" aria-label={`选择 ${i.title}`} className="mr-2 align-middle" checked={Boolean(checked[i.targetId])} onChange={e=>setChecked({...checked,[i.targetId]:e.target.checked})}/>:null}{kinds[i.kind]} · {i.title}</strong><span>{i.dueAt?formatDateTime(i.dueAt):'无截止日'} · {states[i.state]}</span></div><p>责任人：{i.name}{!i.active?'（账号或岗位已停用，须交接）':!i.acceptedAt?' · 尚未确认承接':' · 已承接'}{i.proposedName?`；待交给 ${i.proposedName}，接收前原责任不变`:''}</p>{i.reason&&<p className="text-muted-foreground">{i.reason}</p>}{d.canWrite&&<div className="flex flex-wrap gap-2">{i.state==='OPEN'&&(i.proposedAssigneeId===d.currentUserId||(!i.proposedAssigneeId&&i.assigneeId===d.currentUserId&&!i.acceptedAt))&&<button disabled={busy} className="btn btn-primary btn-sm" onClick={()=>void run(()=>changeWork({id:i.id,revision:i.revision,action:'ACCEPT'}))}>确认承接</button>}{(i.state==='OPEN'?['PROPOSE','RESCHEDULE','COMPLETE','CANCEL'] as const:['REOPEN'] as const).map(a=><button key={a} disabled={busy} className="btn btn-secondary btn-sm" onClick={()=>openWork(i,a)}>{{PROPOSE:'交接责任',RESCHEDULE:'改期',COMPLETE:'办结',CANCEL:'取消事项',REOPEN:'重新办理'}[a]}</button>)}</div>}</article>)}{!items.length&&<p className="text-sm text-muted-foreground">当前范围内没有待办事项。</p>}
 {d.canWrite&&Object.values(checked).some(Boolean)&&<div className="flex flex-wrap items-center gap-2 border-t pt-3"><span className="text-sm text-muted-foreground">已选 {Object.values(checked).filter(Boolean).length} 项任务</span><button disabled={busy} className="btn btn-secondary btn-sm" onClick={()=>{setBatchReason('');setBatchOpen(true);}}>批量办结（须填统一处置结果）</button></div>}
 <Dialog open={batchOpen} onOpenChange={v=>{if(!v&&!busy)setBatchOpen(false);}}><DialogContent><DialogHeader><DialogTitle>批量办结所选任务</DialogTitle><DialogDescription>仅任务类型可批量办结（期限、开庭、保全不在批量范围）；逐项走与单条办结相同的责任链，统一填写处置结果并留痕，单条失败不影响其余。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={async e=>{e.preventDefault();if(!batchReason.trim()){toast.error('请填写统一处置结果');return;}setBusy(true);try{const res=await completeTasksBatch({ids:Object.entries(checked).filter(([,v])=>v).map(([k])=>k),reason:batchReason});const done=res.results.filter(r=>r.ok).length,failed=res.results.filter(r=>!r.ok);toast.success(`已办结 ${done} 项`);if(failed.length)toast.error(`${failed.length} 项失败：${failed[0].error}`);setBatchOpen(false);setChecked({});router.refresh();}catch(err){toast.error(err instanceof Error?err.message:'批量办结失败');}finally{setBusy(false);}}}><Textarea aria-label="统一处置结果或原因" required value={batchReason} onChange={e=>setBatchReason(e.target.value)} placeholder="如：年度整理统一核销旧待办"/><button disabled={busy} className="btn btn-primary" type="submit">确认批量办结</button></form></DialogContent></Dialog>
 <Dialog open={mode!==null} onOpenChange={v=>{if(!v&&!busy)setMode(null);}}><DialogContent><DialogHeader><DialogTitle>{mode==='handover'?'主办交接':mode==='urgent'?'登记收案紧急事项':'处理事项'}</DialogTitle><DialogDescription>变更保留原事项及处理记录；交给他人须由接收人确认。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={submit}>
 {mode==='handover'&&<><Label htmlFor="handover-matter">案件</Label><select id="handover-matter" className="w-full rounded border p-2" required value={selectedMatter} onChange={e=>{setMatter(e.target.value);setEmergency(eligible.find(m=>m.id===e.target.value)?.ownerId!==d.currentUserId);}}>{eligible.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select>{d.emergency&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={emergency} onChange={e=>setEmergency(e.target.checked)}/>按应急接管立即明确新责任</label>}</>}
 {mode==='urgent'&&<><Label htmlFor="urgent-title">事项</Label><Input id="urgent-title" required value={title} onChange={e=>setTitle(e.target.value)}/><Label htmlFor="urgent-kind">类型</Label><select id="urgent-kind" className="w-full rounded border p-2" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="DEADLINE">期限</option><option value="HEARING">开庭</option><option value="TASK">紧急任务</option></select></>}
 {(mode==='handover'||mode==='urgent'||action==='PROPOSE')&&<><Label htmlFor="work-person">接收人 / 责任人</Label><select id="work-person" className="w-full rounded border p-2" required value={person} onChange={e=>setPerson(e.target.value)}><option value="">请选择</option>{d.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></>}
 {(mode==='urgent'||mode==='work'&&action==='RESCHEDULE')&&<><Label htmlFor="work-date">日期与时间（北京时间）</Label><Input id="work-date" required type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></>}
 <Label htmlFor="work-reason">依据、处理原因及通知情况</Label><Textarea id="work-reason" required value={reason} onChange={e=>setReason(e.target.value)}/><button disabled={busy} className="btn btn-primary" type="submit">保存并留痕</button></form></DialogContent></Dialog></section>;
}
