import {randomUUID} from 'node:crypto';import {Prisma} from '@prisma/client';import {z} from 'zod';import {resolveRoleUser} from '@/lib/roles/service';import {scopeFor} from '@/lib/roles/catalog';import {assertLiveAssignees,fingerprint} from './workflow';import {auditTx} from '@/server/audit';
import { ActionError } from "@/lib/action-error";
export async function intakeHandoverReady(db:Prisma.TransactionClient){const [r]=await db.$queryRaw<{ready:boolean}[]>`SELECT to_regclass('public."IntakeHandover"') IS NOT NULL AS ready`;return r?.ready===true;}
async function actor(db:Prisma.TransactionClient,id:string){await db.$queryRaw`SELECT 1 AS locked FROM pg_advisory_xact_lock(72606101)`;const u=await db.user.findUniqueOrThrow({where:{id},select:{role:true,active:true}}),r=await resolveRoleUser(id,u.role,db);if(!u.active||!r.enabled)throw new ActionError('账号或岗位不可用');return r;}
export async function intakeHandoverSnapshot(db:Prisma.TransactionClient,id:string){const i=await db.intake.findUniqueOrThrow({where:{id},select:{id:true,title:true,status:true,ownerUserId:true,coUserIds:true,createdById:true}});const urgent=await db.$queryRaw<{id:string;title:string;assigneeId:string;revision:number;dueAt:Date}[]>`SELECT id,title,"assigneeId",revision,"dueAt" FROM "IntakeUrgentItem" WHERE "intakeId"=${id} AND state='OPEN' ORDER BY id`;return {intake:i,urgent};}
async function transfer(db:Prisma.TransactionClient,intakeId:string,from:string,to:string,accepted:boolean){await assertLiveAssignees(db,[to]);const i=await db.intake.findUniqueOrThrow({where:{id:intakeId}});if(!['INTAKE','NEEDS_REVISION','PENDING_CONFIRMATION'].includes(i.status))throw new ActionError('收案已结束或转案');await db.intake.update({where:{id:intakeId},data:{ownerUserId:to,coUserIds:i.coUserIds.filter(id=>id!==to),...(i.status==='PENDING_CONFIRMATION'?{status:'NEEDS_REVISION'}:{})}});await db.$executeRaw`UPDATE "Intake" SET "workflowRevision"="workflowRevision"+1 WHERE id=${intakeId}`;await db.$executeRaw`UPDATE "IntakeUrgentItem" SET "assigneeId"=${to},"proposedAssigneeId"=NULL,"acceptedAt"=${accepted?new Date():null},revision=revision+1 WHERE "intakeId"=${intakeId} AND "assigneeId"=${from} AND state='OPEN'`;}
export async function requestIntakeHandoverTx(db:Prisma.TransactionClient,userId:string,input:{intakeId:string;toUserId:string;emergency:boolean;reason:string}){
 const d=z.object({intakeId:z.string().cuid(),toUserId:z.string().cuid(),emergency:z.boolean(),reason:z.string().trim().min(1).max(1500)}).parse(input),role=await actor(db,userId);if(!await intakeHandoverReady(db))throw new ActionError('收案交接尚未启用');const before=await intakeHandoverSnapshot(db,d.intakeId),from=before.intake.ownerUserId??before.intake.createdById;
 if(!['INTAKE','NEEDS_REVISION','PENDING_CONFIRMATION'].includes(before.intake.status))throw new ActionError('收案已结束或转案');if(d.emergency?scopeFor(role,'matters.transfer')!=='ALL':from!==userId||(role.role==='CUSTOM'&&!scopeFor(role,'matters.write')))throw new ActionError('交接仅限当前主办，应急接管须独立授权');if(from===d.toUserId)throw new ActionError('接收人与主办相同');await assertLiveAssignees(db,[d.toUserId]);const [count]=await db.$queryRaw<{n:bigint}[]>`SELECT COUNT(*) AS n FROM "IntakeHandover" WHERE "intakeId"=${d.intakeId} AND status='PENDING'`;if(Number(count.n))throw new ActionError('已有待承接收案交接');
 if(d.emergency)await transfer(db,d.intakeId,from,d.toUserId,false);const fp=fingerprint(d.emergency?await intakeHandoverSnapshot(db,d.intakeId):before),id=randomUUID();await db.$executeRaw`INSERT INTO "IntakeHandover" (id,"intakeId","fromUserId","toUserId","initiatedById",emergency,reason,snapshot,fingerprint) VALUES (${id},${d.intakeId},${from},${d.toUserId},${userId},${d.emergency},${d.reason},${JSON.stringify(before)}::jsonb,${fp})`;
 await auditTx(db,{userId,action:'INTAKE_HANDOVER_REQUEST',targetType:'Intake',targetId:d.intakeId,detail:{fromUserId:from,toUserId:d.toUserId,emergency:d.emergency,reason:d.reason}});await db.notification.create({data:{userId:d.toUserId,type:'SYSTEM',priority:'URGENT',title:'收案交接待承接',content:`${before.intake.title}；${d.reason}`,href:'/schedule',refType:'IntakeHandover',refId:id}});return {id};
}
export async function decideIntakeHandoverTx(db:Prisma.TransactionClient,userId:string,id:string,revision:number,decision:'ACCEPT'|'CANCEL'|'REFRESH',reason:string){
 const role=await actor(db,userId);const [h]=await db.$queryRaw<{intakeId:string;fromUserId:string;toUserId:string;initiatedById:string;revision:number;status:string;emergency:boolean;fingerprint:string}[]>`SELECT * FROM "IntakeHandover" WHERE id=${id} FOR UPDATE`;if(!h||h.status!=='PENDING'||h.revision!==revision)throw new ActionError('交接已变化');const current=await intakeHandoverSnapshot(db,h.intakeId);
 if(decision==='REFRESH'){if(h.initiatedById!==userId&&!(h.emergency&&scopeFor(role,'matters.transfer')==='ALL'))throw new ActionError('仅发起人可刷新');await db.$executeRaw`UPDATE "IntakeHandover" SET snapshot=${JSON.stringify(current)}::jsonb,fingerprint=${fingerprint(current)},revision=revision+1 WHERE id=${id}`;}
 else if(decision==='ACCEPT'){if(h.toUserId!==userId)throw new ActionError('仅接收人可以承接');await assertLiveAssignees(db,[userId]);if(fingerprint(current)!==h.fingerprint)throw new ActionError('清单已变化，请刷新交接单');if(!h.emergency)await transfer(db,h.intakeId,h.fromUserId,userId,true);else await db.$executeRaw`UPDATE "IntakeUrgentItem" SET "acceptedAt"=NOW(),revision=revision+1 WHERE "intakeId"=${h.intakeId} AND "assigneeId"=${userId} AND state='OPEN'`;await db.$executeRaw`UPDATE "IntakeHandover" SET status='ACCEPTED',revision=revision+1,"reviewedAt"=NOW() WHERE id=${id}`;}
 else {
  if(h.emergency){
   // 兜底出边：与案件交接一致，接收人失能时由持全所责任交接权限者撤销；原主办仍有效则回转，否则仅解除锁定。
   if(scopeFor(role,'matters.transfer')!=='ALL')throw new ActionError('应急接管已生效，仅持全所责任交接权限者可撤销');if(!reason.trim())throw new ActionError('请填写撤销原因');
   try{await transfer(db,h.intakeId,h.toUserId,h.fromUserId,false);}catch{/* 原主办已不可承接或收案已结束：仅解除待接收锁定 */}
  } else {if(![h.initiatedById,h.toUserId].includes(userId)||!reason.trim())throw new ActionError('须由发起人或接收人填写退回原因');}
  await db.$executeRaw`UPDATE "IntakeHandover" SET status='CANCELLED',revision=revision+1,"reviewedAt"=NOW() WHERE id=${id}`;
 }
 await auditTx(db,{userId,action:`INTAKE_HANDOVER_${decision}`,targetType:'Intake',targetId:h.intakeId,detail:{handoverId:id,reason}});return {ok:true};
}
export async function assertNoPendingIntakeHandover(db:Prisma.TransactionClient,intakeId:string){if(!await intakeHandoverReady(db))return;const [r]=await db.$queryRaw<{n:bigint}[]>`SELECT COUNT(*) AS n FROM "IntakeHandover" WHERE "intakeId"=${intakeId} AND status='PENDING'`;if(Number(r.n))throw new ActionError('请先完成收案责任交接再送审或转案');}
