/** 独立测试库中的更正及分成全流程；不修改主库，不发送外部消息。 */
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Prisma, PrismaClient } from "@prisma/client";
import { registerBillingTx,registerReceiptTx,confirmReceiptTx } from "../src/server/finance/ledger-registration";
import { allocateLedgerTx } from "../src/server/finance/ledger-mutations";
import { submitCorrectionTx,decideCorrectionTx,settleCommissionTx,commissionPositions } from "../src/server/finance/ledger-corrections";
import { type CorrectionInput } from "../src/lib/finance/corrections";
import { readFinanceFacts,periodReceipts,sumAmounts } from "../src/server/finance/facts";
import { readLedger } from "../src/server/finance/ledger-storage";
const config=new PrismaClient({log:[]}), database=process.env.WORKFLOW_TRIAL_DATABASE??'lawlink_workflow_trial_20260919_ef1a255e', prefix=`correction-${randomUUID().slice(0,8)}`;
let db:PrismaClient;let stage="connect";const results:string[]=[];
const owner=`${prefix}-owner`,finance=`${prefix}-finance`,admin=`${prefix}-admin`,confirmer=`${prefix}-confirm`,corrector=`${prefix}-correct`,stranger=`${prefix}-stranger`;
const now=new Date(), old=new Date("2026-08-01T00:00:00+08:00");
const options={isolationLevel:Prisma.TransactionIsolationLevel.Serializable,timeout:20000};
const tx=<T>(f:(t:Prisma.TransactionClient)=>Promise<T>)=>db.$transaction(f,options);
async function reject(name:string,fn:()=>Promise<unknown>,pattern:RegExp){await assert.rejects(fn,pattern);results.push(name);}
const auditFailure=(client:Prisma.TransactionClient)=>new Proxy(client,{get(target,p){if(p==="auditLog")return{create:async()=>{throw new Error("SYNTHETIC_AUDIT_FAILURE");}};return Reflect.get(target,p);}});
async function main(){assert.match(database,/^lawlink_workflow_trial_\d{8}_[a-f0-9]{8}$/);
 const url=new URL(process.env.DATABASE_URL!);assert.notEqual(url.pathname,`/${database}`);url.pathname=`/${database}`;db=new PrismaClient({datasources:{db:{url:url.toString()}},log:[]});
 const [identity]=await db.$queryRaw<{name:string}[]>`SELECT current_database() AS name`;assert.equal(identity.name,database);
 for(const [id,role] of [[owner,"LAWYER"],[finance,"FINANCE"],[admin,"ASSISTANT"],[stranger,"LAWYER"]] as const)await db.user.create({data:{id,role,name:"更正验收人员",email:`${id}@example.invalid`,passwordHash:"NO-LOGIN",systemRole:id===admin?"SUPER_ADMIN":"NONE",managerAuthorized:id===admin}});
 for(const [id,key] of [[confirmer,"finance.confirm"],[corrector,"finance.correct"]]){const role=await db.roleDefinition.create({data:{name:id,normalizedName:id,permissions:{create:[{permissionKey:key,scope:"ALL"}]}}});await db.user.create({data:{id,role:"CUSTOM",roleDefinitionId:role.id,name:"独立权限验收",email:`${id}@example.invalid`,passwordHash:"NO-LOGIN"}});}
 async function fixture(amount="100000"){
  const m=await db.matter.create({data:{internalCode:randomUUID(),title:prefix,ownerId:owner}});
  await db.commissionPlan.create({data:{matterId:m.id,userId:owner,percent:30,active:true}});
  const b=await tx(t=>registerBillingTx(t,owner,{matterId:m.id,title:"原始合同",moneyKind:"LAWYER_FEE",amount,signedAt:old,installments:[{title:"原始应收",amount,dueState:"UNKNOWN"}]}));
  const ar=await db.receivable.findFirstOrThrow({where:{billingId:b.id}});
  const fee=await tx(t=>registerReceiptTx(t,owner,{matterId:m.id,amount,moneyKind:"LAWYER_FEE",occurredAt:old}));await tx(t=>confirmReceiptTx(t,finance,fee.id));
  const p=await db.payment.findFirstOrThrow({where:{feeEntryId:fee.id}});
  await tx(t=>allocateLedgerTx(t,owner,{paymentId:p.id,revision:0,kind:"RECEIVABLE",items:[{targetId:ar.id,amount}]}));
  const inv=await db.invoiceRequest.create({data:{matterId:m.id,amount,status:"ISSUED",requestedById:owner,invoiceNo:randomUUID()}});
  await tx(t=>allocateLedgerTx(t,owner,{paymentId:p.id,revision:1,kind:"INVOICE",items:[{targetId:inv.id,amount}]}));
  const [link]=await db.$queryRaw<{id:string}[]>`SELECT id FROM "InvoicePaymentAllocation" WHERE "paymentId"=${p.id}`;
  const alloc=await db.allocation.findFirstOrThrow({where:{paymentId:p.id}});
  return {m,ar,p,alloc,link,fee};
 }
 const f=await fixture(), other=await fixture();
 const input=(over:Partial<CorrectionInput>={}):CorrectionInput=>({targetId:f.p.id,revision:2,type:"REFUND",debtTreatment:"KEEP_DEBT",amount:"20000",occurredAt:now,reason:"退还多收部分",voucherReference:"合成退款凭据",allocationReversals:[{targetId:f.alloc.id,amount:"20000"}],invoiceReversals:[{targetId:f.link.id,amount:"20000"}],waivers:[],...over});
 stage="request-validations";
 await reject("无关律师不能申请",()=>tx(t=>submitCorrectionTx(t,stranger,input())),/无权/);
 await reject("不能超额退款",()=>tx(t=>submitCorrectionTx(t,owner,input({amount:"100001"}))),/超过原收款/);
 await reject("必须明确撤回核销",()=>tx(t=>submitCorrectionTx(t,owner,input({allocationReversals:[]}))),/撤回足额核销/);
 await reject("必须明确撤回票款",()=>tx(t=>submitCorrectionTx(t,owner,input({invoiceReversals:[]}))),/撤回足额票款/);
 await reject("不能撤回跨案核销",()=>tx(t=>submitCorrectionTx(t,owner,input({allocationReversals:[{targetId:other.alloc.id,amount:"20000"}]}))),/不属于/);
 await reject("不能减免跨案应收",()=>tx(t=>submitCorrectionTx(t,owner,input({debtTreatment:"WAIVE_DEBT",waivers:[{targetId:other.ar.id,amount:"20000"}]}))),/本案/);
 await reject("免除额不能小于退款",()=>tx(t=>submitCorrectionTx(t,owner,input({debtTreatment:"WAIVE_DEBT",waivers:[{targetId:f.ar.id,amount:"10000"}]}))),/必须等于/);
 await reject("撤回金额不能超过更正额",()=>tx(t=>submitCorrectionTx(t,owner,input({allocationReversals:[{targetId:f.alloc.id,amount:"20001"}]}))),/超过本次/);
 await reject("误录冲销必须剩余全额",()=>tx(t=>submitCorrectionTx(t,owner,input({type:"REVERSAL"}))),/全部剩余/);
 await reject("未来实际日期拒绝",()=>tx(t=>submitCorrectionTx(t,owner,input({occurredAt:new Date(Date.now()+86400000)}))),/不能在未来/);
 const c=await tx(t=>submitCorrectionTx(t,owner,input()));
 assert.equal((await readLedger(db,[f.m.id])).summary.netReceived,"100000.00");results.push("待确认不改变余额");
 const decide=(id:string,who=finance,decision:"CONFIRMED"|"REJECTED"|"CANCELLED"="CONFIRMED")=>tx(t=>decideCorrectionTx(t,who,{id,revision:0,decision,note:"合成核对"}));
 await reject("管理权及超级管理员不能确认更正",()=>decide(c.id,admin),/独立财务执行/);
 await reject("实收确认权不包含更正确认",()=>decide(c.id,confirmer),/财务权限/);
 await reject("提交人不能自行确认除非另有授权",()=>decide(c.id,owner),/独立财务执行/);
 const before=await readLedger(db,[f.m.id]);
 await reject("更正确认审计失败整体回滚",()=>tx(t=>decideCorrectionTx(auditFailure(t),finance,{id:c.id,revision:0,decision:"CONFIRMED"})),/SYNTHETIC_AUDIT_FAILURE/);
 assert.deepEqual((await readLedger(db,[f.m.id])).summary,before.summary);
 assert.equal((await db.$queryRaw<{status:string}[]>`SELECT status FROM "FinanceCorrection" WHERE id=${c.id}`)[0].status,"PENDING");
 assert.equal(Number((await db.$queryRaw<{n:bigint}[]>`SELECT COUNT(*) AS n FROM "FinanceCorrectionEffect" WHERE "correctionId"=${c.id}`)[0].n),0);
 // 支付发生在申请前，避免有意触发申请快照失效。
 await decide(c.id,owner,"CANCELLED");results.push("申请人可撤销且保留记录");
 let pos=(await commissionPositions(db,[f.m.id]))[0];
 await reject("到账确认权不包含分成结算",()=>tx(t=>settleCommissionTx(t,confirmer,{commissionEntryId:pos.id,revision:pos.revision,kind:"PAID",amount:"30000",occurredAt:now,voucherReference:"pay"})),/财务权限/);
 await reject("分成支付审计失败整体回滚",()=>tx(t=>settleCommissionTx(auditFailure(t),finance,{commissionEntryId:pos.id,revision:pos.revision,kind:"PAID",amount:"30000",occurredAt:now,voucherReference:"故障回滚"})),/SYNTHETIC_AUDIT_FAILURE/);
 assert.equal((await commissionPositions(db,[f.m.id]))[0].paid.toFixed(2),"0.00");
 const paidPair=await Promise.allSettled([tx(t=>settleCommissionTx(t,finance,{commissionEntryId:pos.id,revision:pos.revision,kind:"PAID",amount:"30000",occurredAt:now,voucherReference:"支付原计提"})),tx(t=>settleCommissionTx(t,finance,{commissionEntryId:pos.id,revision:pos.revision,kind:"PAID",amount:"30000",occurredAt:now,voucherReference:"并发支付"}))]);
 assert.equal(paidPair.filter(p=>p.status==='fulfilled').length,1);results.push("分成并发支付只成功一次并留凭据");
 await reject("分成重复支付被版本阻止",()=>tx(t=>settleCommissionTx(t,finance,{commissionEntryId:pos.id,revision:pos.revision,kind:"PAID",amount:"30000",occurredAt:now,voucherReference:"重复"})),/已变化/);
 const c2=await tx(t=>submitCorrectionTx(t,owner,input()));
 // 改变后续方案不改变原计提快照。
 await db.commissionPlan.updateMany({where:{matterId:f.m.id},data:{percent:50}});
 const pair=await Promise.allSettled([decide(c2.id,corrector),decide(c2.id,corrector)]);
 assert.equal(pair.filter(p=>p.status==='fulfilled').length,1);results.push("自定义更正确认权限有效且并发只成功一次");
 let ledger=await readLedger(db,[f.m.id]);assert.equal(ledger.summary.outstanding,"20000.00");assert.equal(ledger.summary.netReceived,"80000.00");assert.equal(ledger.invoices[0].linked.toFixed(2),"80000.00");results.push("保留债权退款恢复应收并撤回票款");
 pos=(await commissionPositions(db,[f.m.id]))[0];assert.equal(pos.accrued.toFixed(2),"24000.00");assert.equal(pos.recoverable.toFixed(2),"6000.00");assert.equal(pos.netPaid.toFixed(2),"30000.00");results.push("原分成按快照调整，实际超付单列待扣回");
 await reject("不能重复确认退款",()=>decide(c2.id),/已处理/);
 await reject("不能超过实际支付额扣回",()=>tx(t=>settleCommissionTx(t,finance,{commissionEntryId:pos.id,revision:pos.revision,kind:"RECOVERED",amount:"30001",occurredAt:now,voucherReference:"超额"})),/超过实际/);
 await tx(t=>settleCommissionTx(t,finance,{commissionEntryId:pos.id,revision:pos.revision,kind:"RECOVERED",amount:"6000",occurredAt:now,voucherReference:"实退六千"}));
 pos=(await commissionPositions(db,[f.m.id]))[0];assert.equal(pos.recoverable.toFixed(2),"0.00");assert.equal(pos.recovered.toFixed(2),"6000.00");results.push("实际扣回后超付消除");
 stage="waiver-discount";
 const waive=await tx(t=>submitCorrectionTx(t,owner,input({revision:3,debtTreatment:"WAIVE_DEBT",waivers:[{targetId:f.ar.id,amount:"20000"}]})));await decide(waive.id);
 ledger=await readLedger(db,[f.m.id]);assert.equal(ledger.summary.receivable,"80000.00");assert.equal(ledger.summary.outstanding,"20000.00");assert.equal(ledger.summary.netReceived,"60000.00");results.push("免除债权退款不新增客户欠款");
 const discount=await tx(t=>submitCorrectionTx(t,owner,{targetId:f.ar.id,revision:3,type:"DISCOUNT",amount:"30000",occurredAt:now,reason:"收费折让",voucherReference:"折让函",allocationReversals:[{targetId:f.alloc.id,amount:"10000"}]}));await decide(discount.id);
 ledger=await readLedger(db,[f.m.id]);assert.equal(ledger.summary.receivable,"50000.00");assert.equal(ledger.summary.outstanding,"0.00");assert.equal(ledger.summary.unallocated,"10000.00");assert.equal(ledger.summary.netReceived,"60000.00");results.push("折让释放超额核销到未分配款，不产生退款");
 stage="reversal";
 const reverse=await tx(t=>submitCorrectionTx(t,owner,input({revision:5,type:"REVERSAL",amount:"60000",allocationReversals:[{targetId:f.alloc.id,amount:"50000"}],invoiceReversals:[{targetId:f.link.id,amount:"60000"}]})));await decide(reverse.id);
 ledger=await readLedger(db,[f.m.id]);assert.equal(ledger.summary.netReceived,"0.00");assert.equal(ledger.summary.outstanding,"50000.00");assert.equal(ledger.invoices[0].linked.toFixed(2),"0.00");pos=(await commissionPositions(db,[f.m.id]))[0];assert.equal(pos.accrued.toFixed(2),"0.00");assert.equal(pos.recoverable.toFixed(2),"24000.00");results.push("冲销剩余全额及派生分成，保留原流水");
 assert.equal((await db.feeEntry.findUniqueOrThrow({where:{id:f.fee.id}})).amount.toFixed(2),"100000.00");assert.equal((await db.payment.findUniqueOrThrow({where:{id:f.p.id}})).amount.toFixed(2),"100000.00");results.push("原始金额不被改写");
 const facts=(await readFinanceFacts(db,{id:f.m.id}))!;assert.equal(sumAmounts(periodReceipts(facts,old,new Date("2026-09-01T00:00:00+08:00"))),100000);assert.equal(sumAmounts(periodReceipts(facts,new Date("2026-09-01T00:00:00+08:00"))),-100000);results.push("跨月退款不改写原收款月份");
 stage="stale-and-rejection";
 const of:CorrectionInput={...input(),targetId:other.p.id,revision:2,allocationReversals:[{targetId:other.alloc.id,amount:"20000"}],invoiceReversals:[{targetId:other.link.id,amount:"20000"}]};
 const stale=await tx(t=>submitCorrectionTx(t,owner,of));
 const op=(await commissionPositions(db,[other.m.id]))[0];await tx(t=>settleCommissionTx(t,finance,{commissionEntryId:op.id,revision:0,kind:"PAID",amount:"1",occurredAt:now,voucherReference:"后续变动"}));
 await reject("申请后账务变化不得按旧快照确认",()=>decide(stale.id),/申请后账务已变化/);
 await reject("其他经办人不能撤销他人申请",()=>decide(stale.id,finance,"CANCELLED"),/只有申请人/);
 await decide(stale.id,finance,"REJECTED");assert.equal((await readLedger(db,[other.m.id])).summary.netReceived,"100000.00");results.push("退回申请不影响余额");
 await reject("已退回申请不能确认",()=>decide(stale.id),/已处理/);
 await db.matter.update({where:{id:other.m.id},data:{status:"ARCHIVED"}});
 await reject("归档案件继续锁定更正",()=>tx(t=>submitCorrectionTx(t,owner,of)),/归档.*收尾权限/);
 const report=join(tmpdir(),`${prefix}.json`);writeFileSync(report,JSON.stringify({database,at:new Date(),status:"PASS",results},null,2));console.log(`PASS: ${results.length} correction and settlement cases; report ${report}`);
}
main().catch(e=>{console.error(`FAIL: stage=${stage}`);console.error(e instanceof Prisma.PrismaClientKnownRequestError?`Prisma ${e.code}`:e instanceof Error?e.message.replace(/postgres(?:ql)?:\/\/\S+/g,"[redacted]"):"Unknown");process.exitCode=1;}).finally(async()=>{if(db)await db.user.updateMany({where:{email:{endsWith:"@example.invalid"},id:{startsWith:prefix}},data:{active:false}});await db?.$disconnect();await config.$disconnect();});
