/** 新财务登记到确认、分配的独立库验收；不修改当前业务库，不发送外部通知。 */
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Prisma, PrismaClient } from "@prisma/client";
import { createIntakeBillingDraftTx,deleteBillingDraftTx,registerExpenseTx,registerBillingTx,signBillingTx,registerReceiptTx,confirmReceiptTx,rejectReceiptTx,confirmDueConditionTx } from "../src/server/finance/ledger-registration";
import { readFinanceFacts,financeTrend } from "../src/server/finance/facts";
import { agingFromFacts } from "../src/server/finance/facts-aging";
import { allocateLedgerTx } from "../src/server/finance/ledger-mutations";
import { readLedger,financeLedgerReady } from "../src/server/finance/ledger-storage";
const config=new PrismaClient({log:[]});
const database=process.env.WORKFLOW_TRIAL_DATABASE??'lawlink_workflow_trial_20260919_ef1a255e';
const prefix=`registration-${randomUUID().slice(0,8)}`;
const results:string[]=[];
let db:PrismaClient;
let stage="connect";
const options={isolationLevel:Prisma.TransactionIsolationLevel.Serializable,timeout:20000};
const now=new Date();
const part=(amount:string,title="分期")=>({title,amount,dueState:"UNKNOWN" as const});
async function main() {
  assert.match(database,/^lawlink_workflow_trial_\d{8}_[a-f0-9]{8}$/);
  const url=new URL(process.env.DATABASE_URL!);assert.notEqual(url.pathname,`/${database}`);url.pathname=`/${database}`;
  db=new PrismaClient({datasources:{db:{url:url.toString()}},log:[]});
  const [identity]=await db.$queryRaw<{name:string}[]>`SELECT current_database() AS name`;assert.equal(identity.name,database);assert(await financeLedgerReady(db));
  const owner=`${prefix}-owner`, finance=`${prefix}-finance`, admin=`${prefix}-admin`, matter=`${prefix}-matter`, other=`${prefix}-other`;
  for(const [id,role] of [[owner,"LAWYER"],[finance,"FINANCE"],[admin,"ASSISTANT"]] as const)await db.user.create({data:{id,role,name:"新流程验收人员",email:`${id}@example.invalid`,passwordHash:"NO-LOGIN",systemRole:id===admin?"SUPER_ADMIN":"NONE"}});
  for(const id of [matter,other])await db.matter.create({data:{id,internalCode:id,title:"新登记闭环验收",ownerId:owner}});
  const tx=<T>(work:(tx:Prisma.TransactionClient)=>Promise<T>)=>db.$transaction(work,options);
  const bill=(amount:string,signedAt:Date|undefined,installments:ReturnType<typeof part>[])=>({matterId:matter,title:"十万元收费",moneyKind:"LAWYER_FEE" as const,amount,signedAt,installments});
  const receipt=(amount:string,moneyKind:"LAWYER_FEE"|"CLIENT_FUNDS"="LAWYER_FEE")=>({matterId:matter,amount,moneyKind,occurredAt:now});
  const auditFailure=(client:Prisma.TransactionClient)=>new Proxy(client,{get(target,p){if(p==="auditLog")return{create:async()=>{throw new Error("SYNTHETIC_AUDIT_FAILURE");}};return Reflect.get(target,p);}});
  async function reject(name:string,work:()=>Promise<unknown>,message:RegExp){await assert.rejects(work,message);results.push(name);}
  stage="billing";
  await reject("分期不齐不得签署",()=>tx(t=>registerBillingTx(t,owner,bill("100000",now,[part("40000")]))),/合计必须等于/);
  assert.equal(await db.billing.count({where:{matterId:matter}}),0);
  await reject("草稿不得提前形成应收",()=>tx(t=>registerBillingTx(t,owner,bill("100000",undefined,[part("100000")]))),/草稿暂不/);
  const draft=await tx(t=>registerBillingTx(t,owner,bill("100000",undefined,[])));
  assert.equal(await db.receivable.count({where:{billingId:draft.id}}),0);results.push("草稿只生成收费安排");
  await tx(t=>signBillingTx(t,owner,{id:draft.id,revision:0,signedAt:now,installments:[part("40000","第一期"),{title:"第二期",amount:"60000",dueState:"CONDITIONAL",dueCondition:"交付成果"}]}));
  const ars=await db.receivable.findMany({where:{billingId:draft.id},orderBy:{amount:"asc"}});assert.equal(ars.length,2);results.push("签署一次生成四万及六万两期");
  await reject("重复签署不重复应收",()=>tx(t=>signBillingTx(t,owner,{id:draft.id,revision:0,signedAt:now,installments:[part("100000")]})),/已签署或发生变化/);
  const free=await tx(t=>registerBillingTx(t,owner,bill("0.00",now,[])));assert.equal(await db.receivable.count({where:{billingId:free.id}}),0);results.push("零收费不创建零额应收");
  await tx(t=>confirmDueConditionTx(t,owner,{id:ars[1].id,revision:0,satisfiedAt:now,note:"合成交付凭证"}));
  await reject("条件成就不能重复确认",()=>tx(t=>confirmDueConditionTx(t,owner,{id:ars[1].id,revision:0,satisfiedAt:now,note:"重复"})),/已确认或应收已变化/);
  await reject("来源合同不能跨案",()=>tx(t=>registerReceiptTx(t,owner,{...receipt("1"),matterId:other,billingId:draft.id})),/来源合同须属于本案/);
  await reject("来源合同不能跨性质",()=>tx(t=>registerReceiptTx(t,owner,{...receipt("1","CLIENT_FUNDS"),billingId:draft.id})),/款项性质相同/);
  await db.commissionPlan.create({data:{matterId:matter,userId:owner,percent:30,active:true}});
  const intakeDraft=await tx(t=>createIntakeBillingDraftTx(t,owner,{matterId:matter,title:"收案带入费用",amount:new Prisma.Decimal(100),schedule:"先付四成，交付后余款"}));
  const intakeBilling=await db.billing.findUniqueOrThrow({where:{id:intakeDraft.id}});
  assert.equal(intakeBilling.status,"DRAFT");assert.equal(intakeBilling.signedAt,null);assert.equal(intakeBilling.schedule,"先付四成，交付后余款");assert.equal(await db.receivable.count({where:{billingId:intakeDraft.id}}),0);results.push("收案费用带入草稿保留约定，不推定签署或应收");
  await reject("已签署收费不能从草稿删除入口删除",()=>tx(t=>deleteBillingDraftTx(t,owner,draft.id)),/已签署或发生变化/);
  await reject("草稿删除审计失败保留原稿",()=>tx(t=>deleteBillingDraftTx(auditFailure(t),owner,intakeDraft.id)),/SYNTHETIC_AUDIT_FAILURE/);
  assert(await db.billing.findUnique({where:{id:intakeDraft.id}}));
  await tx(t=>deleteBillingDraftTx(t,owner,intakeDraft.id));assert.equal(await db.billing.findUnique({where:{id:intakeDraft.id}}),null);results.push("无关联收费草稿可审计删除");
  await reject("未来到账不能当成已实收",()=>tx(t=>registerReceiptTx(t,owner,{...receipt("100"),occurredAt:new Date(Date.now()+86400000)})),/不能在未来/);
  const expense=await tx(t=>registerExpenseTx(t,owner,{...receipt("12.34"),moneyKind:"EXPENSE_RECOVERY",note:"合成垫付支出"}));
  assert.equal((await db.feeEntry.findUniqueOrThrow({where:{id:expense.id}})).type,"COST");assert.equal(await db.payment.count({where:{feeEntryId:expense.id}}),0);assert.equal(await db.feeEntry.count({where:{parentFeeEntryId:expense.id}}),0);results.push("支出独立登记，不产生实收或分成");
  stage="pending-and-confirmation";
  const first=await tx(t=>registerReceiptTx(t,owner,{...receipt("40000"),billingId:draft.id}));
  const own=await tx(t=>registerReceiptTx(t,finance,receipt("2","CLIENT_FUNDS")));
  for(const entry of [first,own])assert.equal((await db.feeEntry.findUniqueOrThrow({where:{id:entry.id}})).confirmState,"PENDING");
  assert.equal(await db.payment.count({where:{matterId:matter}}),0);assert.equal(await db.timelineEvent.count({where:{matterId:matter,eventType:"FEE_RECEIVED"}}),0);assert.equal(await db.feeEntry.count({where:{matterId:matter,type:"COMMISSION"}}),0);results.push("经办与财务本人登记都只待确认，无实收分成时间线");
  await reject("普通经办不能确认到账",()=>tx(t=>confirmReceiptTx(t,owner,first.id)),/仅具备/);
  await reject("系统管理身份不能确认到账",()=>tx(t=>confirmReceiptTx(t,admin,first.id)),/仅具备/);
  await reject("审计失败则确认整体回滚",()=>tx(t=>confirmReceiptTx(auditFailure(t),finance,first.id)),/SYNTHETIC_AUDIT_FAILURE/);
  assert.equal((await db.feeEntry.findUniqueOrThrow({where:{id:first.id}})).confirmState,"PENDING");assert.equal(await db.payment.count({where:{feeEntryId:first.id}}),0);assert.equal(await db.feeEntry.count({where:{parentFeeEntryId:first.id}}),0);assert.equal(await db.timelineEvent.count({where:{refId:first.id}}),0);
  const race=await Promise.allSettled([tx(t=>confirmReceiptTx(t,finance,first.id)),tx(t=>confirmReceiptTx(t,finance,first.id))]);assert.equal(race.filter(r=>r.status==="fulfilled").length,1);assert.equal(await db.payment.count({where:{feeEntryId:first.id}}),1);assert.equal(await db.timelineEvent.count({where:{refId:first.id}}),1);results.push("并发确认仅一笔实收一次分成一次时间线");
  const [share]=await db.$queryRaw<{amount:Prisma.Decimal;commissionRateSnapshot:Prisma.Decimal;commissionBaseSnapshot:Prisma.Decimal}[]>`SELECT amount,"commissionRateSnapshot","commissionBaseSnapshot" FROM "FeeEntry" WHERE "parentFeeEntryId"=${first.id}`;
  assert.equal(share.amount.toFixed(2),"12000.00");assert.equal(share.commissionRateSnapshot.toFixed(2),"30.00");assert.equal(share.commissionBaseSnapshot.toFixed(2),"40000.00");results.push("律师费计提保留原比例和基数");
  await tx(t=>confirmReceiptTx(t,finance,own.id));assert.equal(await db.feeEntry.count({where:{parentFeeEntryId:own.id}}),0);results.push("代收款确认不计提律师分成");
  const second=await tx(t=>registerReceiptTx(t,owner,receipt("60000")));await tx(t=>confirmReceiptTx(t,finance,second.id));
  const p1=await db.payment.findFirstOrThrow({where:{feeEntryId:first.id}}),p2=await db.payment.findFirstOrThrow({where:{feeEntryId:second.id}});
  await tx(t=>allocateLedgerTx(t,owner,{paymentId:p1.id,revision:0,kind:"RECEIVABLE",items:[{targetId:ars[0].id,amount:"40000"}]}));assert.equal((await readLedger(db,[matter])).summary.outstanding,"60000.00");
  await tx(t=>allocateLedgerTx(t,owner,{paymentId:p2.id,revision:0,kind:"RECEIVABLE",items:[{targetId:ars[1].id,amount:"60000"}]}));assert.equal((await readLedger(db,[matter])).summary.outstanding,"0.00");results.push("真实登记确认后四万再六万，核销余额归零");
  const facts=await readFinanceFacts(db,{id:matter});assert(facts);
  assert.equal(facts.lawyerSummary.netReceived,"100000.00");assert.equal(facts.lawyerSummary.outstanding,"0.00");assert.equal(facts.summary.clientFundsReceived,"2.00");
  assert.equal(financeTrend(facts,1)[0].received,100000);assert.equal(agingFromFacts(facts).totalOutstanding,0);
  const emptyScope=await readFinanceFacts(db,{id:other});assert(emptyScope);assert.equal(emptyScope.lawyerSummary.netReceived,"0.00");
  results.push("统计事实源在月图、余额和账龄一致，代收款及范围外数据隔离");
  stage="rejection-and-rollback";
  const rejected=await tx(t=>registerReceiptTx(t,owner,receipt("100")));
  await reject("退回必须有原因",()=>tx(t=>rejectReceiptTx(t,finance,rejected.id," ")),/填写退回原因/);
  await reject("退回审计失败不删除登记",()=>tx(t=>rejectReceiptTx(auditFailure(t),finance,rejected.id,"错误")),/SYNTHETIC_AUDIT_FAILURE/);
  assert(await db.feeEntry.findUnique({where:{id:rejected.id}}));
  await tx(t=>rejectReceiptTx(t,finance,rejected.id,"合成凭证不符"));assert.equal(await db.feeEntry.findUnique({where:{id:rejected.id}}),null);assert.equal(await db.notification.count({where:{refId:rejected.id,userId:owner,title:"实收登记被退回"}}),1);results.push("退回记录原因并同事务通知登记人");
  const before=await db.billing.count({where:{matterId:matter}});await reject("收费审计失败不留下应收孤项",()=>tx(t=>registerBillingTx(auditFailure(t),owner,bill("100",now,[part("100")]))),/SYNTHETIC_AUDIT_FAILURE/);assert.equal(await db.billing.count({where:{matterId:matter}}),before);
  const report=join(tmpdir(),`${prefix}.json`);writeFileSync(report,JSON.stringify({database,at:new Date().toISOString(),results,status:"PASS"},null,2));console.log(`PASS: ${results.length} registration workflow cases; ${report}`);
}
main().catch(e=>{console.error(`FAIL: ${stage}`);console.error(e instanceof Prisma.PrismaClientKnownRequestError?`Prisma ${e.code}`:e instanceof Error?e.message.replace(/postgres(?:ql)?:\/\/\S+/g,"[redacted]"):"Unknown error");process.exitCode=1;}).finally(async()=>{if(db)await db.user.updateMany({where:{email:{endsWith:"@example.invalid"},id:{startsWith:prefix}},data:{active:false}});await db?.$disconnect();await config.$disconnect();});
