/** 独立库跨模块验收：收案交接、发票外部更正、合同覆盖与冲突门禁。 */
import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {Prisma,PrismaClient} from '@prisma/client';import {writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {requestIntakeHandoverTx,decideIntakeHandoverTx,assertNoPendingIntakeHandover} from '../src/server/intakes/handover';import {createUrgentTx,scanAdditionalWorkReminders} from '../src/server/reminders/urgent';import {readWorkRows,changeWorkTx} from '../src/server/reminders/responsibility';import {adjustInvoiceTx} from '../src/server/invoices/adjustments';import {registerBillingTx,registerReceiptTx,confirmReceiptTx} from '../src/server/finance/ledger-registration';import {allocateLedgerTx} from '../src/server/finance/ledger-mutations';import {readLedger} from '../src/server/finance/ledger-storage';import {bindContractScopeTx,assertProcedureCovered} from '../src/server/finance/ledger-contracts';import {recordMatterReviewTx,assertMatterReviewCurrent} from '../src/server/conflicts/matter-review';
const init=new PrismaClient({log:[]}),database=process.env.WORKFLOW_TRIAL_DATABASE??'lawlink_workflow_trial_20260919_ef1a255e',prefix=`boundaries-${randomUUID().slice(0,8)}`;let db:PrismaClient;let stage='connect';const users:string[]=[],results:string[]=[];
const tx=<T>(fn:(t:Prisma.TransactionClient)=>Promise<T>)=>db.$transaction(fn,{isolationLevel:'Serializable',timeout:20000});const bad=async(name:string,fn:()=>Promise<unknown>,pattern:RegExp)=>{await assert.rejects(fn,pattern);results.push(name);};
async function main(){assert.match(database,/^lawlink_workflow_trial_\d{8}_[a-f0-9]{8}$/);const url=new URL(process.env.DATABASE_URL!);assert.notEqual(url.pathname,`/${database}`);url.pathname=`/${database}`;db=new PrismaClient({datasources:{db:{url:url.toString()}},log:[]});assert.equal((await db.$queryRaw<{name:string}[]>`SELECT current_database() AS name`)[0].name,database);const [owner,receiver]=await Promise.all(['owner','receiver'].map(p=>db.user.create({data:{name:prefix+p,email:`${prefix}-${p}@example.invalid`,passwordHash:'NO-LOGIN',role:'LAWYER'}})));users.push(owner.id,receiver.id);const role=await db.roleDefinition.create({data:{name:prefix,normalizedName:prefix,permissions:{create:['matters.transfer','finance.correct','finance.confirm','finance.write','invoices.process'].map(permissionKey=>({permissionKey,scope:'ALL'}))}}}),fin=await db.user.create({data:{name:prefix+'fin',email:`${prefix}-fin@example.invalid`,passwordHash:'NO-LOGIN',role:'CUSTOM',roleDefinitionId:role.id}});users.push(fin.id);
 const now=new Date(),i=await db.intake.create({data:{title:prefix,ownerUserId:owner.id,createdById:owner.id,status:'PENDING_CONFIRMATION'}}),u=await tx(t=>createUrgentTx(t,owner.id,{intakeId:i.id,title:'紧急答辩',dueAt:now,kind:'DEADLINE',assigneeId:owner.id,basis:'合成法院来件'}));
 stage='intake-handover';const h=await tx(t=>requestIntakeHandoverTx(t,owner.id,{intakeId:i.id,toUserId:receiver.id,emergency:false,reason:'承办分工调整'}));assert.equal((await db.intake.findUniqueOrThrow({where:{id:i.id}})).ownerUserId,owner.id);await bad('交接待接收期间不得送审或转案',()=>tx(t=>assertNoPendingIntakeHandover(t,i.id)),/先完成/);await tx(t=>decideIntakeHandoverTx(t,receiver.id,h.id,0,'ACCEPT','核对紧急事项'));const changed=await db.intake.findUniqueOrThrow({where:{id:i.id}});assert.equal(changed.ownerUserId,receiver.id);assert.equal(changed.createdById,owner.id);assert.equal(changed.status,'NEEDS_REVISION');assert.equal((await readWorkRows(db)).find(r=>r.id===u.id)?.assigneeId,receiver.id);results.push('收案主办与紧急事项同步承接，保留登记人并重新送审');
 await db.user.update({where:{id:receiver.id},data:{active:false}});await bad('普通人员不能应急接管',()=>tx(t=>requestIntakeHandoverTx(t,owner.id,{intakeId:i.id,toUserId:owner.id,emergency:true,reason:'接管'})),/独立授权/);const e=await tx(t=>requestIntakeHandoverTx(t,fin.id,{intakeId:i.id,toUserId:owner.id,emergency:true,reason:'原主办安全停用'}));assert.equal((await db.intake.findUniqueOrThrow({where:{id:i.id}})).ownerUserId,owner.id);await tx(t=>decideIntakeHandoverTx(t,owner.id,e.id,0,'ACCEPT','核对承接'));results.push('收案应急接管不依赖原主办登录');
 stage='urgent-reminders';await scanAdditionalWorkReminders(db,now);const notices=await db.notification.count({where:{userId:owner.id,refId:u.id,id:{startsWith:'workreminder_'}}});assert.equal(notices,1);await scanAdditionalWorkReminders(db,now);assert.equal(await db.notification.count({where:{userId:owner.id,refId:u.id,id:{startsWith:'workreminder_'}}}),1);const work=(await readWorkRows(db)).find(w=>w.id===u.id)!;await tx(t=>changeWorkTx(t,owner.id,{id:work.id,revision:work.revision,action:'CANCEL',reason:'已移交客户并告知期限'}));await scanAdditionalWorkReminders(db,now);assert.equal(await db.notification.count({where:{userId:owner.id,refId:u.id,id:{startsWith:'workreminder_'},read:false}}),0);results.push('紧急事项即时扫描去重，取消后原提醒失效');
 const m=await db.matter.create({data:{title:prefix,internalCode:prefix,ownerId:owner.id}}),doc=await db.document.create({data:{name:'合成外部红冲凭证',path:'no-file-test-only',uploadedById:fin.id,matterId:m.id,category:'OTHER'}}),invoice=await db.invoiceRequest.create({data:{matterId:m.id,amount:100000,status:'ISSUED',invoiceNo:prefix,requestedById:owner.id,issuedAt:now}});
 const receipt=await tx(t=>registerReceiptTx(t,owner.id,{matterId:m.id,moneyKind:'LAWYER_FEE',amount:40000,occurredAt:now}));await tx(t=>confirmReceiptTx(t,fin.id,receipt.id));const payment=await db.payment.findFirstOrThrow({where:{feeEntryId:receipt.id}});await tx(t=>allocateLedgerTx(t,owner.id,{paymentId:payment.id,revision:0,kind:'INVOICE',items:[{targetId:invoice.id,amount:40000}]}));const [link]=await db.$queryRaw<{id:string}[]>`SELECT id FROM "InvoicePaymentAllocation" WHERE "invoiceId"=${invoice.id}`;
 stage='invoice-adjustment';const base={invoiceId:invoice.id,kind:'RED' as const,amount:'70000',occurredAt:now,reference:prefix,reason:'实际红冲凭证',documentId:doc.id,reversals:[]};await bad('原律师无权确认外部发票更正',()=>tx(t=>adjustInvoiceTx(t,owner.id,base)),/独立财务执行权限/);await bad('红冲后票面不足须明确解除票款关联',()=>tx(t=>adjustInvoiceTx(t,fin.id,base)),/解除足额/);
 await tx(t=>adjustInvoiceTx(t,fin.id,{...base,reversals:[{id:link.id,amount:10000}]}));let ledger=await readLedger(db,[m.id]);assert.equal(ledger.invoices[0].amount.toFixed(2),'30000.00');assert.equal(ledger.invoices[0].linked.toFixed(2),'30000.00');assert.equal(ledger.summary.netReceived,'40000.00');assert.equal((await db.invoiceRequest.findUniqueOrThrow({where:{id:invoice.id}})).amount.toFixed(2),'100000.00');results.push('部分红冲保持原票，解除关联不制造退款');
 await bad('红冲后不允许再次按原票面超额关联',()=>tx(t=>allocateLedgerTx(t,owner.id,{paymentId:payment.id,revision:2,kind:'INVOICE',items:[{targetId:invoice.id,amount:1}]})),/未关联金额/);
 await tx(t=>adjustInvoiceTx(t,fin.id,{...base,kind:'VOID',amount:'30000',reference:prefix+'-void',reversals:[{id:link.id,amount:'30000'}]}));ledger=await readLedger(db,[m.id]);assert.equal(ledger.invoices[0].amount.toFixed(2),'0.00');assert.equal(ledger.summary.netReceived,'40000.00');results.push('作废剩余票面并解除关联，原实收保持');
 const [old,newInvoice]=await Promise.all(['old','new'].map(label=>db.invoiceRequest.create({data:{matterId:m.id,amount:20000,status:'ISSUED',requestedById:owner.id,invoiceNo:prefix+label}})));await tx(t=>adjustInvoiceTx(t,fin.id,{...base,invoiceId:old.id,kind:'REPLACE',amount:20000,reference:prefix+'-replace',replacementInvoiceId:newInvoice.id}));ledger=await readLedger(db,[m.id]);assert.equal(ledger.invoices.find(i=>i.id===old.id)?.amount.toFixed(2),'0.00');assert.equal(ledger.invoices.find(i=>i.id===newInvoice.id)?.amount.toFixed(2),'20000.00');results.push('换开关联新票，不重复累计旧票面');
 stage='scope-and-conflict';await db.party.create({data:{matterId:m.id,name:prefix+'独有委托方',role:'CLIENT_PARTY',partyType:'NATURAL_PERSON'}});const p=await db.matterProcedure.create({data:{matterId:m.id,type:'FIRST_INSTANCE',order:1,status:'PENDING'}}),bill=await tx(t=>registerBillingTx(t,owner.id,{matterId:m.id,title:'零收费代理',amount:0,moneyKind:'LAWYER_FEE',signedAt:now,installments:[]}));await bad('程序无合同覆盖不能开始办理',()=>tx(t=>assertProcedureCovered(t,p.id)),/尚无有效委托覆盖/);await tx(t=>bindContractScopeTx(t,owner.id,{billingId:bill.id,revision:0,procedureId:p.id,state:'COVERED',note:'签署委托明确本程序公益代理，免收律师费'}));await tx(t=>assertProcedureCovered(t,p.id));await bad('合同范围确认后仍须冲突复核',()=>tx(t=>assertMatterReviewCurrent(t,m.id)),/动态冲突复核/);await tx(t=>recordMatterReviewTx(t,owner.id,m.id));await tx(t=>assertMatterReviewCurrent(t,m.id));results.push('明确零收费依据并完成当前冲突复核后可以承接');await db.party.create({data:{matterId:m.id,name:prefix+'新增对方',role:'OPPOSING_PARTY',partyType:'NATURAL_PERSON'}});await bad('新增主体使原承接核查失效',()=>tx(t=>assertMatterReviewCurrent(t,m.id)),/主体或代理范围已变化/);
 const output=join(tmpdir(),`${prefix}.json`);writeFileSync(output,JSON.stringify({database,results},null,2));console.log(`PASS: ${results.length} cross-workflow boundary checks; ${output}`);
}
main().catch(e=>{console.error(`FAIL ${stage}: ${e instanceof Prisma.PrismaClientKnownRequestError?`${e.code} ${String(e.meta?.message??'')}`:e.message}`);process.exitCode=1;}).finally(async()=>{if(db){await db.user.updateMany({where:{id:{in:users}},data:{active:false}});await db.$disconnect();}await init.$disconnect();});
