/** 独立合成数据库：主办交接、事项责任、改期取消及收案紧急事项。 */
import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {Prisma,PrismaClient} from '@prisma/client';import {writeFileSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {readWorkRows,changeWorkTx} from '../src/server/reminders/responsibility';import {requestHandoverTx,decideHandoverTx,refreshHandoverTx} from '../src/server/matters/handover';import {createUrgentTx,assertNoOpenIntakeUrgency,transferIntakeUrgency} from '../src/server/reminders/urgent';import {refreshScheduleReminder} from '../src/server/reminders/schedule';import {responsibilityCounts} from '../src/server/reminders/offboarding';
const init=new PrismaClient({log:[]}),database=process.env.WORKFLOW_TRIAL_DATABASE??'lawlink_workflow_trial_20260919_ef1a255e',prefix=`handover-${randomUUID().slice(0,8)}`;let db:PrismaClient;let stage='connect';let users:string[]=[];const results:string[]=[];
const tx=<T>(fn:(t:Prisma.TransactionClient)=>Promise<T>)=>db.$transaction(fn,{isolationLevel:'Serializable',timeout:20000});
const bad=async(name:string,fn:()=>Promise<unknown>,pattern:RegExp)=>{await assert.rejects(fn,pattern);results.push(name);};
async function main(){assert.match(database,/^lawlink_workflow_trial_\d{8}_[a-f0-9]{8}$/);const url=new URL(process.env.DATABASE_URL!);assert.notEqual(url.pathname,`/${database}`);url.pathname=`/${database}`;db=new PrismaClient({datasources:{db:{url:url.toString()}},log:[]});assert.equal((await db.$queryRaw<{name:string}[]>`SELECT current_database() AS name`)[0].name,database);
 const people=await Promise.all(['owner','receiver','admin'].map(p=>db.user.create({data:{name:prefix+p,email:`${prefix}-${p}@example.invalid`,passwordHash:'NO-LOGIN',role:'LAWYER',systemRole:p==='admin'?'SUPER_ADMIN':'NONE',managerAuthorized:p==='admin'}})));users=people.map(p=>p.id);const [owner,receiver,admin]=users;
 const role=await db.roleDefinition.create({data:{name:prefix,normalizedName:prefix,permissions:{create:{permissionKey:'matters.transfer',scope:'ALL'}}}});const emergency=await db.user.create({data:{name:prefix+'emergency',email:`${prefix}-emergency@example.invalid`,passwordHash:'NO-LOGIN',role:'CUSTOM',roleDefinitionId:role.id}});users.push(emergency.id);
 const m=await db.matter.create({data:{title:prefix,internalCode:prefix,ownerId:owner,members:{create:{userId:owner,role:'LEAD'}}}});const p=await db.matterProcedure.create({data:{matterId:m.id,type:'FIRST_INSTANCE',order:1,leadLawyerId:owner,status:'IN_PROGRESS'}});const now=new Date();
 stage='creation-trigger';const task=await db.task.create({data:{matterId:m.id,title:'合成任务',dueAt:now}});const deadline=await db.deadline.create({data:{procedureId:p.id,title:'合成期限',dueAt:now}});const hearing=await db.hearing.create({data:{procedureId:p.id,title:'合成开庭',startsAt:now}});
 let rows=(await readWorkRows(db)).filter(w=>w.matterId===m.id);assert.equal(rows.length,3);assert(rows.every(w=>w.assigneeId===owner&&!w.acceptedAt));assert.equal((await db.task.findUniqueOrThrow({where:{id:task.id}})).assigneeId,owner);results.push('三个创建入口均原子生成默认责任且承接与已读分开');
 stage='normal-handover';const h=await tx(t=>requestHandoverTx(t,owner,{matterId:m.id,toUserId:receiver,reason:'更换承办律师'}));assert.equal((await db.matter.findUniqueOrThrow({where:{id:m.id}})).ownerId,owner);results.push('待接收期间原主办继续负责');
 await bad('无关管理员不能代为接受',()=>tx(t=>decideHandoverTx(t,admin,h.id,0,'ACCEPTED','')),/接收人/);
 const pairs=await Promise.allSettled([tx(t=>decideHandoverTx(t,receiver,h.id,0,'ACCEPTED','')),tx(t=>decideHandoverTx(t,receiver,h.id,0,'ACCEPTED',''))]);assert.equal(pairs.filter(r=>r.status==='fulfilled').length,1);assert.equal((await db.matter.findUniqueOrThrow({where:{id:m.id}})).ownerId,receiver);rows=(await readWorkRows(db)).filter(w=>w.matterId===m.id);assert(rows.every(w=>w.assigneeId===receiver&&w.acceptedAt));assert.equal((await db.matterProcedure.findUniqueOrThrow({where:{id:p.id}})).leadLawyerId,receiver);results.push('并发只完成一次，主办程序任务期限开庭同步移交');
 stage='item-lifecycle';const w=rows.find(w=>w.targetId===hearing.id)!;await tx(t=>changeWorkTx(t,receiver,{id:w.id,revision:w.revision,action:'RESCHEDULE',dueAt:new Date(now.getTime()+86400000),reason:'法院通知改期'}));assert.equal((await db.hearing.findUniqueOrThrow({where:{id:hearing.id}})).startsAt.getTime(),now.getTime()+86400000);let row=(await readWorkRows(db)).find(r=>r.id===w.id)!;assert.equal(row.acceptedAt,null);await tx(t=>changeWorkTx(t,receiver,{id:row.id,revision:row.revision,action:'CANCEL',reason:'收到取消通知并已告知客户'}));assert.equal(await refreshScheduleReminder('Hearing',hearing.id,now,db),null);assert(await db.hearing.findUnique({where:{id:hearing.id}}));results.push('改期重置承接，取消停用提醒并保留原开庭');
 const tw=(await readWorkRows(db)).find(w=>w.targetId===task.id)!;await tx(t=>changeWorkTx(t,receiver,{id:tw.id,revision:tw.revision,action:'PROPOSE',assigneeId:owner,reason:'分工调整'}));assert.equal((await db.task.findUniqueOrThrow({where:{id:task.id}})).assigneeId,receiver);row=(await readWorkRows(db)).find(w=>w.id===tw.id)!;await tx(t=>changeWorkTx(t,owner,{id:row.id,revision:row.revision,action:'ACCEPT'}));assert.equal((await db.task.findUniqueOrThrow({where:{id:task.id}})).assigneeId,owner);results.push('单项责任须接收后转移');
 stage='emergency';await db.user.update({where:{id:receiver},data:{active:false}});assert((await responsibilityCounts(db)).get(receiver)!>0);await bad('系统及管理身份不附带应急权限',()=>tx(t=>requestHandoverTx(t,admin,{matterId:m.id,toUserId:owner,emergency:true,reason:'安全停用后接管'})),/独立/);const e=await tx(t=>requestHandoverTx(t,emergency.id,{matterId:m.id,toUserId:owner,emergency:true,reason:'账号已停用，防止期限无人负责'}));assert.equal((await db.matter.findUniqueOrThrow({where:{id:m.id}})).ownerId,owner);results.push('停用责任保留可见，独立授权可立即接管');
 await bad('生效应急接管不得撤回停用责任人',()=>tx(t=>decideHandoverTx(t,emergency.id,e.id,0,'CANCELLED','撤回')),/不能撤销/);
 const dw=(await readWorkRows(db)).find(w=>w.targetId===deadline.id)!;await tx(t=>changeWorkTx(t,owner,{id:dw.id,revision:dw.revision,action:'RESCHEDULE',dueAt:new Date(now.getTime()+2*86400000),reason:'核对新期限'}));await bad('清单变动阻止用旧清单承接',()=>tx(t=>decideHandoverTx(t,owner,e.id,0,'ACCEPTED','')),/清单已变化/);await tx(t=>refreshHandoverTx(t,emergency.id,e.id,0));await tx(t=>decideHandoverTx(t,owner,e.id,1,'ACCEPTED',''));results.push('清单变化后须刷新再接收');
 stage='intake-urgent';const intake=await db.intake.create({data:{title:prefix,ownerUserId:owner,createdById:owner}});const urgent=await tx(t=>createUrgentTx(t,owner,{intakeId:intake.id,title:'收案时已迫近的答辩期限',dueAt:now,kind:'DEADLINE',assigneeId:owner,basis:'法院通知，已告知委托方'}));await bad('紧急事项未处置禁止拒绝接案',()=>tx(t=>assertNoOpenIntakeUrgency(t,intake.id)),/紧急事项/);await tx(t=>transferIntakeUrgency(t,intake.id,m.id));const u=(await readWorkRows(db)).find(w=>w.id===urgent.id)!;assert.equal(u.matterId,m.id);assert.equal(u.intakeId,intake.id);results.push('转案保留同一紧急事项ID及责任');await tx(t=>changeWorkTx(t,owner,{id:u.id,revision:u.revision,action:'COMPLETE',reason:'已提交答辩并告知客户'}));await tx(t=>assertNoOpenIntakeUrgency(t,intake.id));results.push('明确完成后可结束收案');
 const output=join(tmpdir(),`${prefix}.json`);writeFileSync(output,JSON.stringify({database,results},null,2));console.log(`PASS: ${results.length} responsibility and handover checks; ${output}`);
}
main().catch(e=>{console.error(`FAIL ${stage}: ${e instanceof Prisma.PrismaClientKnownRequestError?`${e.code} ${String(e.meta?.message??'')}`:e.message}`);process.exitCode=1;}).finally(async()=>{if(db){await db.user.updateMany({where:{id:{in:users}},data:{active:false}});await db.$disconnect();}await init.$disconnect();});
