/** 仅独立合成测试库：合同版本、应收同步和支出冲销。 */
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Prisma,PrismaClient} from '@prisma/client';
import {registerBillingTx,registerExpenseTx} from '../src/server/finance/ledger-registration';
import {draftAmendmentTx,activateAmendmentTx,cancelAmendmentTx} from '../src/server/finance/ledger-contracts';
import {submitCorrectionTx,decideCorrectionTx} from '../src/server/finance/ledger-corrections';
import {readFinanceFacts,sumAmounts} from '../src/server/finance/facts';
import {readLedger} from '../src/server/finance/ledger-storage';
import type {ContractTermsInput} from '../src/lib/finance/contracts';
const init=new PrismaClient({log:[]}),database=process.env.WORKFLOW_TRIAL_DATABASE??'lawlink_workflow_trial_20260919_ef1a255e',prefix=`contracts-${randomUUID().slice(0,8)}`,owner=`${prefix}-owner`,finance=`${prefix}-finance`,stranger=`${prefix}-stranger`;
let db:PrismaClient;let stage='connect';const results:string[]=[];const date=new Date('2026-09-01T00:00:00+08:00');
const tx=<T>(f:(t:Prisma.TransactionClient)=>Promise<T>)=>db.$transaction(f,{isolationLevel:'Serializable',timeout:20000});
const bad=async(name:string,fn:()=>Promise<unknown>,pattern:RegExp)=>{await assert.rejects(fn,pattern);results.push(name);};
async function main(){assert.match(database,/^lawlink_workflow_trial_\d{8}_[a-f0-9]{8}$/);
 const url=new URL(process.env.DATABASE_URL!);assert.notEqual(url.pathname,`/${database}`);url.pathname=`/${database}`;db=new PrismaClient({datasources:{db:{url:url.toString()}},log:[]});assert.equal((await db.$queryRaw<{name:string}[]>`SELECT current_database() AS name`)[0].name,database);
 for(const [id,role] of [[owner,'LAWYER'],[finance,'FINANCE'],[stranger,'LAWYER']] as const)await db.user.create({data:{id,name:prefix,role,email:`${id}@example.invalid`,passwordHash:'NO-LOGIN'}});
 const matter=await db.matter.create({data:{title:prefix,internalCode:prefix,ownerId:owner}}),other=await db.matter.create({data:{title:prefix,internalCode:prefix+'other',ownerId:owner}});
 const doc=await db.document.create({data:{matterId:matter.id,name:'合成补充协议',path:'synthetic-no-file',uploadedById:owner}}),otherDoc=await db.document.create({data:{matterId:other.id,name:'跨案材料',path:'synthetic-no-file',uploadedById:owner}});
 const proc=await db.matterProcedure.create({data:{matterId:matter.id,type:'FIRST_INSTANCE',order:1}});
 const b=await tx(t=>registerBillingTx(t,owner,{matterId:matter.id,title:'原合同',moneyKind:'LAWYER_FEE',amount:'100000',signedAt:date,installments:[{title:'原应收',amount:'100000',dueState:'UNKNOWN'}]}));
 const ar=await db.receivable.findFirstOrThrow({where:{billingId:b.id}});
 const terms=(over:Partial<ContractTermsInput>={}):ContractTermsInput=>({sourceBillingId:b.id,sourceRevision:0,title:'合成补充协议',type:'ADDITION',amount:'20000',signedAt:date,effectiveAt:date,reason:'新增二审服务',documentIds:[doc.id],scopes:[{procedureId:proc.id,state:'COVERED',note:'覆盖一审服务'}],installments:[{title:'追加一期',amount:'20000',dueState:'UNKNOWN'}],...over});
 stage='contract-validation';
 await bad('跨案依据拒绝',()=>tx(t=>draftAmendmentTx(t,owner,terms({documentIds:[otherDoc.id]}))),/本案有效材料/);
 await bad('无关人员不能改合同',()=>tx(t=>draftAmendmentTx(t,stranger,terms())),/无权/);
 await bad('追加分期合计不符拒绝',()=>tx(t=>draftAmendmentTx(t,owner,terms({installments:[]}))),/差额/);
 const addition=await tx(t=>draftAmendmentTx(t,owner,terms()));assert.equal(sumAmounts((await readFinanceFacts(db,{id:matter.id}))!.billings.map(b=>({amount:b.contractAmount}))),100000);results.push('草稿不覆盖现行总额');
 const pair=await Promise.allSettled([tx(t=>activateAmendmentTx(t,owner,addition.id,0)),tx(t=>activateAmendmentTx(t,owner,addition.id,0))]);assert.equal(pair.filter(p=>p.status==='fulfilled').length,1);results.push('并发确认只有一次生效');
 let facts=(await readFinanceFacts(db,{id:matter.id}))!;assert.equal(sumAmounts(facts.billings.map(b=>({amount:b.contractAmount}))),120000);assert.equal(facts.summary.receivable,'120000.00');results.push('追加只增差额，原合同保留且总额不重复');
 await bad('旧版本不能继续变更',()=>tx(t=>draftAmendmentTx(t,owner,terms())),/变化|末版/);
 const reduction=await tx(t=>draftAmendmentTx(t,owner,terms({sourceBillingId:addition.id,sourceRevision:1,type:'REPLACEMENT',amount:'90000',installments:[],reductions:[{receivableId:ar.id,revision:0,amount:'30000'}]})));
 await bad('普通律师不能确认费用调减',()=>tx(t=>activateAmendmentTx(t,owner,reduction.id,0)),/独立财务/);
 await tx(t=>activateAmendmentTx(t,finance,reduction.id,0));facts=(await readFinanceFacts(db,{id:matter.id}))!;assert.equal(sumAmounts(facts.billings.map(b=>({amount:b.contractAmount}))),90000);assert.equal(facts.summary.receivable,'90000.00');results.push('替代总价只计九万并仅调减三万应收');
 const corrections=await db.$queryRaw<{count:bigint}[]>`SELECT COUNT(*) AS count FROM "FinanceCorrection" WHERE "sourceBillingId"=${reduction.id}`;assert.equal(Number(corrections[0].count),1);
 await bad('不能重复生效或重复调减',()=>tx(t=>activateAmendmentTx(t,finance,reduction.id,0)),/已处理/);
 const cancelled=await tx(t=>draftAmendmentTx(t,owner,terms({sourceBillingId:reduction.id,sourceRevision:1,type:'SCOPE_ONLY',amount:'0',installments:[]})));await tx(t=>cancelAmendmentTx(t,owner,cancelled.id,0));await bad('作废草稿不能生效',()=>tx(t=>activateAmendmentTx(t,owner,cancelled.id,1)),/已处理/);
 await bad('终止须有事项与交接说明',()=>tx(t=>draftAmendmentTx(t,owner,terms({sourceBillingId:reduction.id,sourceRevision:1,type:'TERMINATION',amount:'90000',installments:[]}))),/终止结算/);
 const ended=await tx(t=>draftAmendmentTx(t,owner,terms({sourceBillingId:reduction.id,sourceRevision:1,type:'TERMINATION',amount:'90000',endsAt:date,completedWork:'已完成一审',handoverWork:'无',installments:[]})));await tx(t=>activateAmendmentTx(t,owner,ended.id,0));await bad('终止后不能续改同条合同链',()=>tx(t=>draftAmendmentTx(t,owner,terms({sourceBillingId:ended.id,sourceRevision:1}))),/终止/);
 stage='expense';const expense=await tx(t=>registerExpenseTx(t,owner,{matterId:matter.id,amount:'1000',moneyKind:'OTHER',occurredAt:date,note:'误录支出'}));
 const input={targetId:expense.id,targetKind:'EXPENSE' as const,revision:0,type:'REVERSAL' as const,amount:'1000',occurredAt:date,reason:'重复登记',voucherReference:'支出核对单'};
 await bad('支出不得部分误录冲销',()=>tx(t=>submitCorrectionTx(t,owner,{...input,amount:'500'})),/全部金额/);
 const request=await tx(t=>submitCorrectionTx(t,owner,input));const before=await readLedger(db,[matter.id]);await tx(t=>decideCorrectionTx(t,finance,{id:request.id,revision:0,decision:'CONFIRMED'}));assert.deepEqual((await readLedger(db,[matter.id])).summary,before.summary);facts=(await readFinanceFacts(db,{id:matter.id}))!;assert.equal(sumAmounts(facts.expenses.map(e=>({amount:e.amount.minus(e.reversed)}))),0);assert.equal((await db.feeEntry.findUniqueOrThrow({where:{id:expense.id}})).amount.toNumber(),1000);results.push('支出冲销保留原额、净支出归零、不增加客户收款');
 await bad('支出不能重复冲销',()=>tx(t=>submitCorrectionTx(t,owner,{...input,revision:1})),/只能一次/);
 console.log(`PASS: ${results.length} contract and expense assertions`);writeFileSync(join(tmpdir(),`${prefix}.json`),JSON.stringify({database,results},null,2));
}
main().catch(e=>{console.error(`FAIL ${stage}: ${e instanceof Prisma.PrismaClientKnownRequestError?e.code:e.message}`);process.exitCode=1;}).finally(async()=>{if(db){await db.user.updateMany({where:{id:{in:[owner,finance,stranger]}},data:{active:false}});await db.$disconnect();}await init.$disconnect();});
