import { fixtureBilling, fixtureReceivable, fixtureReceipt } from "./workflow-finance-fixtures";
/** 仅连接已授权的独立试迁移库；合成样本保留，不修改业务库/Schema、不发通知。 */
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Prisma, PrismaClient } from "@prisma/client";
import { allocateLedgerTx } from "../src/server/finance/ledger-mutations";
import { readLedger, financeLedgerReady } from "../src/server/finance/ledger-storage";
import { type AllocateLedgerInput } from "../src/lib/finance/ledger";

// Prisma 初始化只加载配置，目标客户端始终显式指定测试库。
const config = new PrismaClient({log:[]});
const database = process.env.WORKFLOW_TRIAL_DATABASE??'lawlink_workflow_trial_20260919_ef1a255e';
const runId = `ledger-${randomUUID().slice(0,8)}`;
const results: string[] = [];
let db: PrismaClient;
let stage = "connect-test-database";
const txOptions = { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, timeout:20000 };
async function main() {
  assert.match(database,/^lawlink_workflow_trial_\d{8}_[a-f0-9]{8}$/);
  const url = new URL(process.env.DATABASE_URL!);
  assert.notEqual(decodeURIComponent(url.pathname.slice(1)),database);
  url.pathname=`/${database}`;url.searchParams.set("schema","public");
  db = new PrismaClient({datasources:{db:{url:url.toString()}},log:[]});
  const [identity] = await db.$queryRaw<{name:string}[]>`SELECT current_database() AS name`;
  assert.equal(identity.name,database);
  assert(await financeLedgerReady(db));
  stage = "fixtures";
  const finance = `${runId}-finance`, owner = `${runId}-owner`, admin = `${runId}-admin`, custom = `${runId}-custom`, ownCase = `${runId}-matter`, otherCase = `${runId}-other`, archivedCase = `${runId}-archived`;
  await db.user.create({data:{id:finance,name:"财务验收人员",email:`${finance}@example.invalid`,passwordHash:"NO-LOGIN",role:"FINANCE"}});
  await db.user.create({data:{id:owner,name:"经办验收人员",email:`${owner}@example.invalid`,passwordHash:"NO-LOGIN",role:"LAWYER"}});
  await db.user.create({data:{id:admin,name:"纯系统管理员验收人员",email:`${admin}@example.invalid`,passwordHash:"NO-LOGIN",role:"ASSISTANT",systemRole:"SUPER_ADMIN"}});
  const role = await db.roleDefinition.create({data:{name:runId,normalizedName:runId,permissions:{create:[{permissionKey:"finance.write",scope:"OWN"},{permissionKey:"finance.read",scope:"OWN"}]}}});
  await db.user.create({data:{id:custom,name:"受限岗位验收人员",email:`${custom}@example.invalid`,passwordHash:"NO-LOGIN",role:"CUSTOM",roleDefinitionId:role.id}});
  for (const id of [ownCase,otherCase,archivedCase]) await db.matter.create({data:{id,internalCode:id,title:"账务闭环合成验收",ownerId:owner,status:id===archivedCase?"ARCHIVED":"IN_PROGRESS"}});
  const bill = await fixtureBilling(db,ownCase,100000);
  const first = await fixtureReceivable(db,ownCase,40000,{billingId:bill.id});
  const second = await fixtureReceivable(db,ownCase,60000,{billingId:bill.id});
  const cross = await fixtureReceivable(db,otherCase,100000);
  const receipt = (matterId:string,amount:number,moneyKind:"LAWYER_FEE"|"CLIENT_FUNDS"="LAWYER_FEE") => fixtureReceipt(db,matterId,amount,owner,finance,{moneyKind});
  const p1 = await receipt(ownCase,40000), p2 = await receipt(ownCase,60000);
  const archived = await receipt(archivedCase,100);
  const invoice = await db.invoiceRequest.create({data:{matterId:ownCase,amount:100000,status:"ISSUED",invoiceNo:runId,requestedById:owner}});
  const allocate = (input: AllocateLedgerInput, actor=finance) => db.$transaction(tx=>allocateLedgerTx(tx,actor,input),txOptions);
  async function rejects(name:string,work:()=>Promise<unknown>,message:RegExp) {
    const before = await db.auditLog.count({where:{userId:{in:[finance,owner,admin,custom]}}});
    await assert.rejects(work,message);
    assert.equal(await db.auditLog.count({where:{userId:{in:[finance,owner,admin,custom]}}}),before);
    results.push(name);
  }
  const allocation = (paymentId:string,revision:number,targetId:string,amount:string):AllocateLedgerInput => ({paymentId,revision,kind:"RECEIVABLE",items:[{targetId,amount}]});
  stage="permissions";
  await rejects("归档门禁保留",()=>allocate(allocation(archived.id,0,first.id,"1")),/归档.*收尾权限/);
  await rejects("纯系统管理员不能操作他案财务",()=>allocate(allocation(p1.id,0,first.id,"1"),admin),/无权处理/);
  await rejects("OWN 岗位不能操作他案财务",()=>allocate(allocation(p1.id,0,first.id,"1"),custom),/无权处理/);
  await rejects("跨案核销拒绝",()=>allocate(allocation(p1.id,0,cross.id,"1")),/不属于同一案件/);
  await rejects("重复目标拒绝",()=>allocate({paymentId:p1.id,revision:0,kind:"RECEIVABLE",items:[{targetId:first.id,amount:"1"},{targetId:first.id,amount:"1"}]}),/只能填写一次/);
  await rejects("超出收款拒绝",()=>allocate(allocation(p1.id,0,second.id,"40000.01")),/超过实收/);
  stage="receipt-allocation-invoice";
  await allocate({paymentId:p1.id,revision:0,kind:"RECEIVABLE",items:[{targetId:first.id,amount:"10000"},{targetId:second.id,amount:"30000"}]},owner);
  let ledger = await readLedger(db,[ownCase]);
  assert.equal(ledger.summary.outstanding,"60000.00");
  results.push("经办可核销本人案件，第一笔 4 万分到两期后剩余 6 万");
  await allocate({paymentId:p1.id,revision:1,kind:"INVOICE",items:[{targetId:invoice.id,amount:"10000"}]});
  ledger = await readLedger(db,[ownCase]);
  assert.equal(ledger.invoices[0].amount.minus(ledger.invoices[0].linked).toFixed(2),"90000.00");
  assert.equal(ledger.payments.find(p=>p.id===p1.id)!.allocatedAmount.toFixed(2),"40000.00");
  results.push("10 万发票关联 1 万仍余 9 万，票款不再次扣减核销额度");
  await rejects("旧版本重放不重复入账",()=>allocate(allocation(p1.id,0,first.id,"10000")),/已变化或请求已处理/);
  await allocate(allocation(p2.id,0,first.id,"15000"));
  await allocate({paymentId:p2.id,revision:1,kind:"RECEIVABLE",items:[{targetId:first.id,amount:"15000"},{targetId:second.id,amount:"30000"}]});
  ledger=await readLedger(db,[ownCase]);
  assert.equal(ledger.summary.outstanding,"0.00");
  assert.equal(ledger.summary.unallocated,"0.00");
  const pair=await db.allocation.findUniqueOrThrow({where:{paymentId_receivableId:{paymentId:p2.id,receivableId:first.id}}});
  assert.equal(pair.amount.toFixed(2),"30000.00");
  results.push("第二笔 6 万完成两期，同一核销关系可累计追加");
  await allocate({paymentId:p1.id,revision:2,kind:"INVOICE",items:[{targetId:invoice.id,amount:"5000"}]});
  ledger=await readLedger(db,[ownCase]);assert.equal(ledger.invoices[0].linked.toFixed(2),"15000.00");
  results.push("同一票款关系可以追加并保留逐次审计");
  stage="races-and-atomicity";
  const raceAr = await fixtureReceivable(db,ownCase,100);
  const raceP = await receipt(ownCase,100);
  const race = await Promise.allSettled([allocate(allocation(raceP.id,0,raceAr.id,"60")),allocate(allocation(raceP.id,0,raceAr.id,"60"))]);
  assert.equal(race.filter(r=>r.status==="fulfilled").length,1);
  assert.equal((await db.payment.findUniqueOrThrow({where:{id:raceP.id}})).allocatedAmount.toFixed(2),"60.00");
  results.push("同版本并发核销只成功一次，无超额分配");
  const auditBefore=await db.auditLog.count({where:{targetId:raceP.id}});
  await assert.rejects(()=>db.$transaction(tx=>allocateLedgerTx(new Proxy(tx,{get(target,prop){if(prop==="auditLog")return {create:async()=>{throw new Error("SYNTHETIC_AUDIT_FAILURE");}};return Reflect.get(target,prop);}}),finance,allocation(raceP.id,1,raceAr.id,"10")),txOptions),/SYNTHETIC_AUDIT_FAILURE/);
  assert.equal((await db.payment.findUniqueOrThrow({where:{id:raceP.id}})).allocatedAmount.toFixed(2),"60.00");
  assert.equal(await db.auditLog.count({where:{targetId:raceP.id}}),auditBefore);
  results.push("审计失败时核销、余额、版本全部回滚");
  const clientPayment=await receipt(ownCase,100,"CLIENT_FUNDS");
  await rejects("代收款不能核销律师费",()=>allocate(allocation(clientPayment.id,0,raceAr.id,"1")),/款项性质相同/);
  await rejects("代收款不能关联律师费发票",()=>allocate({paymentId:clientPayment.id,revision:0,kind:"INVOICE",items:[{targetId:invoice.id,amount:"1"}]}),/仅支持/);
  const invalidSource = await receipt(ownCase,10);
  await db.$executeRaw`UPDATE "FeeEntry" SET "moneyKind"='OTHER' WHERE id=${invalidSource.feeId}`;
  await rejects("来源性质不符不能分配",()=>allocate(allocation(invalidSource.id,0,raceAr.id,"1")),/来源流水不一致/);
  await assert.rejects(()=>readLedger(db,[ownCase]),/实收来源不一致/);
  results.push("异常来源不会被静默排除后生成不完整报表");
  await db.$executeRaw`UPDATE "FeeEntry" SET "moneyKind"='LAWYER_FEE' WHERE id=${invalidSource.feeId}`;
  await db.user.update({where:{id:owner},data:{active:false}});
  await rejects("账号停用实时生效",()=>allocate(allocation(raceP.id,1,raceAr.id,"1"),owner),/已停用/);
  // 所有验收用户最后均停用；样本保留供复核，不清库。
  await db.user.updateMany({where:{id:{in:[finance,owner,admin,custom]}},data:{active:false}});
  const path=join(tmpdir(),`${runId}-result.json`);
  writeFileSync(path,JSON.stringify({database,runId,at:new Date().toISOString(),results,status:"PASS"},null,2)+"\n");
  console.log(`PASS: ${results.length} workflow cases in ${database}; synthetic run ${runId}; report ${path}`);
}
main().catch(error=>{console.error(`FAIL: stage=${stage}; database=${database}; run=${runId}`);if(error instanceof assert.AssertionError)console.error(error.message.split("\n")[0]);else if(error instanceof Prisma.PrismaClientKnownRequestError)console.error(`Prisma code: ${error.code}`);else console.error(error instanceof Error ? error.message.replace(/postgres(?:ql)?:\/\/\S+/g,"[redacted]"):"Unknown error");process.exitCode=1;}).finally(async()=>{await db?.$disconnect();await config.$disconnect();});
