"use server";
import {assertClosureReady,closureReady} from "./closure";
import {buildArchiveManifest} from "./export";
import {scopeFor} from "@/lib/roles/catalog";
import { roleMutation, checkRoleMutation, resolveRoleUser } from "@/lib/roles/service";

import { approvalTransaction, approvalAudit, assertApprovalItem, requireApprovalRoute } from "@/lib/approvals/service";


import { revalidatePath } from "next/cache";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requireSession } from "@/lib/auth/session";
import { audit } from "@/server/audit";
import { notifyRoleApprovers } from "@/server/notifications/approval";
import { createNotification } from "@/server/notifications/create";
import { checklistForCategory } from "@/lib/archive/checklists";
import {
  ARCHIVE_MANUAL_CHECKS,
  ARCHIVE_SNAPSHOT_VERSION,
  assertArchiveApprovalReady,
  parseArchiveSnapshot,
  type ArchiveReviewSnapshot
} from "@/lib/archive/snapshot";
import { nextArchiveNo } from "@/lib/archive/archive-no";
import { assertMatterWritable } from "@/lib/archive/guard";
import { assertCanLeadMatter, matterReadVisibilityFilter } from "@/lib/permissions";
import { renderArchiveCover, renderArchiveCatalog } from "./render";
import { archiveApproveSchema, archiveSubmitSchema, type ArchiveApproveInput, type ArchiveSubmitInput, CLOSED_REASON_CN } from "./schemas";
import { getArchivePolicy } from "./policy";
import { createArchiveDocumentSnapshots, verifyArchivePolicySource, verifyArchiveSnapshotDocuments } from "./verification";
import { matterHref } from "@/lib/matters/route";
import { revalidateMatter } from "@/server/matters/route";
import { recordTimelineEvent } from "@/server/timeline/record";

/**
 * v0.9.4 归档：完整流程
 *   1. 权限：本案主办 / 协办提交，审批人按事项授权
 *   2. 校验 checklist 缺必填项 → 若有且未 forceWithMissing 则拒绝
 *   3. 生成 archiveNo
 *   4. 渲染卷宗封皮 → 入 ARCHIVE 卷宗
 *   5. 渲染卷宗目录（含已生成的封皮自身可选不入目录）
 *   6. 创建 ArchiveRecord
 *   7. Matter status=ARCHIVED + archivedAt + closedAt
 *   8. TimelineEvent + audit
 */
export async function archiveMatter(input: ArchiveSubmitInput) {
  const session = await requireSession("archive.submit");
  const data = archiveSubmitSchema.parse(input);

  const initial=await prisma.matter.findUniqueOrThrow({where:{id:data.matterId},select:{status:true}});
  const supplement=initial.status==='ARCHIVED';
  if(supplement){if(scopeFor(session.user,'archive.supplement')!=='OWN')throw new Error('补充归档须独立授权');}
  else await assertMatterWritable(data.matterId);
  await assertCanLeadMatter(session.user.id, data.matterId, "仅案件主办/协办可以提交归档申请");

  const matter = await prisma.matter.findUnique({
    where: { id: data.matterId },
    select: { id: true, status: true, category: true, internalCode: true, title: true }
  });
  if (!matter) throw new Error("案件不存在");
  await requireApprovalRoute({ action: "ARCHIVE_APPROVE", category: matter.category, requesterId: session.user.id });
  const parent=supplement?await prisma.archiveRecord.findFirst({where:{matterId:matter.id,status:"APPROVED"},orderBy:{archivedAt:"asc"},select:{id:true}}):null;
  if(supplement&&!parent)throw new Error("缺少已批准原归档");
  await assertClosureReady(prisma,matter.id,undefined,{supplement});

  const pending = await prisma.archiveRecord.findFirst({
    where: { matterId: matter.id, status: "PENDING_REVIEW" },
    select: { archiveNo: true }
  });
  if (pending) throw new Error(`本案已有待审归档申请 ${pending.archiveNo}，请先完成该申请`);

  const policy = await getArchivePolicy();
  if (!policy.configured || !policy.sourceFileId || !policy.sourceFileName || !policy.sourceFileSha256) {
    throw new Error("律所尚未配置可核验的归档制度，请管理员先在“管理后台—归档制度”完成配置");
  }

  const checklist = checklistForCategory(matter.category);
  const submittedItems = checklist.items.filter((item) => !item.autoGenerated).map((item) => {
    const submitted = data.checklistItems[item.id] ?? {
      status: "MISSING" as const,
      documentIds: [],
      note: ""
    };
    const documentIds = [...new Set(submitted.documentIds)];
    if (submitted.status === "ATTACHED" && documentIds.length === 0) {
      throw new Error(`“${item.label}”标记为已有材料，但没有关联实际文件`);
    }
    if (submitted.status !== "ATTACHED" && documentIds.length > 0) {
      throw new Error(`“${item.label}”已关联文件，不能同时标记为缺失或不适用`);
    }
    if (submitted.status === "NOT_APPLICABLE" && !submitted.note) {
      throw new Error(`请说明“${item.label}”不适用的理由`);
    }
    if (item.required && submitted.status !== "ATTACHED") {
      if (!data.forceWithMissing) throw new Error(`必交项“${item.label}”没有实际材料`);
      if (!submitted.note) throw new Error(`请逐项说明必交项“${item.label}”的缺项或不适用理由`);
    }
    return {
      id: item.id,
      label: item.label,
      required: item.required,
      autoGenerated: false,
      status: submitted.status,
      note: submitted.note,
      documentIds
    };
  });

  const manualChecks = ARCHIVE_MANUAL_CHECKS.map((item) => {
    const submitted = data.manualChecks[item.id];
    if (!submitted?.confirmed) throw new Error(`请完成归档核验：“${item.label}”`);
    return { id: item.id, label: item.label, confirmed: true, note: submitted.note };
  });
  const selectedDocumentIds = [...new Set(submittedItems.flatMap((item) => item.documentIds))];
  const itemIdsByDocumentId = new Map<string, string[]>();
  for (const item of submittedItems) {
    for (const documentId of item.documentIds) {
      const itemIds = itemIdsByDocumentId.get(documentId) ?? [];
      itemIdsByDocumentId.set(documentId, [...itemIds, item.id]);
    }
  }
  const missingItems = submittedItems
    .filter((item) => item.required && item.status !== "ATTACHED")
    .map((item) => item.id);

  // 渲染必须在事务外（涉及文件系统 + 加密）。先渲染再事务里建记录。
  const now = new Date();
  const archiveNo = await nextArchiveNo(prisma, matter.category, now);

  const extras = {
    archiveNo,
    closedReason: data.closedReason,
    completedAt: data.completedAt,
    archivedAt: now,
    judgmentSummary: data.judgmentSummary || undefined
  };

  let coverDocId: string;
  try {
    coverDocId = await renderArchiveCover(prisma, {
      matterId: matter.id,
      userId: session.user.id,
      extras
    });
  } catch (err) {
    throw new Error(`渲染卷宗封皮失败：${err instanceof Error ? err.message : String(err)}`);
  }

  let catalogDocId: string;
  try {
    catalogDocId = await renderArchiveCatalog(prisma, {
      matterId: matter.id,
      userId: session.user.id,
      extras,
      excludeDocIds: [coverDocId],
      documentIds: selectedDocumentIds
    });
  } catch (err) {
    // 封皮已落库；目录失败时回滚封皮文档（标记软删）。律师重试可重新生成。
    await roleMutation(session.user, "archive.submit", async roleDb => roleDb.document.update({
      where: { id: coverDocId },
      data: { deletedAt: new Date() }
    })).catch(() => null);
    throw new Error(`渲染卷宗目录失败：${err instanceof Error ? err.message : String(err)}`);
  }

  itemIdsByDocumentId.set(coverDocId, ["archive_cover"]);
  itemIdsByDocumentId.set(catalogDocId, ["archive_catalog"]);
  const allDocumentIds = [...selectedDocumentIds, coverDocId, catalogDocId];
  let documents;
  try {
    documents = await createArchiveDocumentSnapshots({
      matterId: matter.id,
      orderedDocumentIds: allDocumentIds,
      itemIdsByDocumentId
    });
  } catch (error) {
    await roleMutation(session.user, "archive.submit", async roleDb => roleDb.document.updateMany({
      where: { id: { in: [coverDocId, catalogDocId] } },
      data: { deletedAt: new Date() }
    })).catch(() => null);
    throw error;
  }
  const previousRecord = await prisma.archiveRecord.findFirst({
    where: { matterId: matter.id, status: "REJECTED" },
    orderBy: { archivedAt: "desc" },
    select: { id: true }
  });
  const excludedDocuments = await prisma.document.findMany({
    where: {
      matterId: matter.id,
      deletedAt: null,
      id: { notIn: allDocumentIds },
      NOT: [{ tags: { has: "卷宗封皮" } }, { tags: { has: "卷宗目录" } }]
    },
    orderBy: { createdAt: "asc" },
    select: { id: true, name: true, size: true, folder: { select: { name: true } } }
  });
  const autoItems = checklist.items.filter((item) => item.autoGenerated).map((item) => ({
    id: item.id,
    label: item.label,
    required: item.required,
    autoGenerated: true,
    status: "AUTO_GENERATED" as const,
    note: "系统按本次送审材料生成",
    documentIds: item.id === "archive_cover" ? [coverDocId] : [catalogDocId]
  }));
  const snapshot: ArchiveReviewSnapshot = {
    schemaVersion: ARCHIVE_SNAPSHOT_VERSION,
    policy: {
      configured: true,
      name: policy.name,
      version: policy.version,
      effectiveAt: policy.effectiveAt,
      sourceFileId: policy.sourceFileId,
      sourceFileName: policy.sourceFileName,
      sourceFileSha256: policy.sourceFileSha256
    },
    checklist: { kind: checklist.kind, title: checklist.title, items: [...submittedItems, ...autoItems] },
    manualChecks,
    documents,
    excludedDocuments: excludedDocuments.map((document) => ({ id: document.id, name: document.name, folderName: document.folder?.name ?? null, size: document.size })),
    documentIds: allDocumentIds,
    submittedAt: now.toISOString(),
    previousRecordId: previousRecord?.id ?? null
  };
  try {
    await verifyArchivePolicySource(snapshot);
  } catch (error) {
    await prisma.document.updateMany({
      where: { id: { in: [coverDocId, catalogDocId] } },
      data: { deletedAt: new Date() }
    }).catch(() => null);
    throw error;
  }

  let submitted;
  try {
    submitted = await prisma.$transaction(async (tx) => {
    await checkRoleMutation(tx, session.user, "archive.submit");
    if(supplement){const actor=await tx.user.findUniqueOrThrow({where:{id:session.user.id},select:{role:true}});if(scopeFor(await resolveRoleUser(session.user.id,actor.role,tx),'archive.supplement')!=='OWN')throw new Error('补充归档须独立授权');}
      const workflow=await assertClosureReady(tx,matter.id,undefined,{supplement});
      const alreadyPending = await tx.archiveRecord.findFirst({
        where: { matterId: matter.id, status: "PENDING_REVIEW" },
        select: { archiveNo: true }
      });
      if (alreadyPending) throw new Error(`本案已有待审归档申请 ${alreadyPending.archiveNo}`);
      const record = await tx.archiveRecord.create({
        data: {
          matterId: matter.id,
          archiveNo,
          summary: data.summary,
          judgmentSummary: data.judgmentSummary || null,
          closedReason: data.closedReason,
          completedAt: data.completedAt,
          checklistJson: snapshot as unknown as Prisma.InputJsonValue,
          missingItems,
          coverDocId,
          catalogDocId,
          archivedBy: session.user.name ?? session.user.id,
          archivedById: session.user.id,
          status: "PENDING_REVIEW",
          reviewedById: null,
          reviewedAt: null
        }
      });
      if(workflow)await tx.$executeRaw`UPDATE "ArchiveRecord" SET "workflowSnapshot"=${JSON.stringify(workflow)}::jsonb,"supplementOfId"=${parent?.id??null} WHERE id=${record.id}`;
      await recordTimelineEvent(tx, {
          matterId: matter.id,
          eventType: "MATTER_ARCHIVE_REQUESTED",
          title: `归档申请已提交（${archiveNo}，待审批）`,
          content: `结案方式：${CLOSED_REASON_CN[data.closedReason]}。送审材料 ${documents.length} 份；${missingItems.length ? `必交缺项 ${missingItems.length} 项。` : "必交项均已关联材料。"}${data.summary}`,
          occurredAt: now
        });
      return record;
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
  } catch (error) {
    await roleMutation(session.user, "archive.submit", async roleDb => roleDb.document.updateMany({
      where: { id: { in: [coverDocId, catalogDocId] } },
      data: { deletedAt: new Date() }
    })).catch(() => null);
    throw error;
  }

  await notifyRoleApprovers({ roles: ["PRINCIPAL_LAWYER"], excludeUserId: session.user.id, title: "新的归档申请待审批", content: archiveNo, href: "/approvals", refType: "ArchiveRecord", refId: submitted.id });

  await audit({
    userId: session.user.id,
    action: "MATTER_ARCHIVE",
    targetType: "Matter",
    targetId: matter.id,
    detail: {
      archiveNo,
      closedReason: data.closedReason,
      missingCount: missingItems.length,
      forced: data.forceWithMissing && missingItems.length > 0,
      attachmentIds: allDocumentIds,
      policyVersion: policy.version
    }
  });

  await revalidateMatter(matter.id);
  revalidatePath("/matters");
  revalidatePath("/archive");
  revalidatePath("/approvals");
  return { ok: true, archiveNo, status: "PENDING_REVIEW" };
}

/**
 * v0.16: 管理员审批通过归档申请（PENDING_REVIEW → APPROVED）
 */
export async function approveArchiveRecord(input: ArchiveApproveInput) {
  const session = await requireSession("approval");
  const data = archiveApproveSchema.parse(input);
  await assertApprovalItem(session.user.id, "ARCHIVE_APPROVE", data.archiveId);

  const record = await prisma.archiveRecord.findUnique({
    where: { id: data.archiveId },
    select: {
      id: true,
      matterId: true,
      status: true,
      completedAt: true,
      archiveNo: true,
      coverDocId: true,
      catalogDocId: true,
      checklistJson: true,
      archivedById: true
    }
  });
  if (!record) throw new Error("归档记录不存在");
  if (record.status !== "PENDING_REVIEW") throw new Error("此归档申请已审批");
  const snapshot = parseArchiveSnapshot(record.checklistJson);
  if (!snapshot) throw new Error("该历史归档申请没有固定实际材料，请驳回后重新提交");
  const requiredIds = assertArchiveApprovalReady({ snapshot, verificationIds: data.verificationIds, exceptionApproved: data.exceptionApproved, note: data.note });
  await verifyArchivePolicySource(snapshot);
  await verifyArchiveSnapshotDocuments(snapshot, record.matterId);

  const now = new Date();
  await approvalTransaction(async (tx) => {
    await assertApprovalItem(session.user.id, "ARCHIVE_APPROVE", data.archiveId, tx);
    let supplementOfId:string|null=null;
    if(await closureReady(tx)){
      const [saved]=await tx.$queryRaw<{workflowSnapshot:{fingerprint:string}|null;supplementOfId:string|null}[]>`SELECT "workflowSnapshot","supplementOfId" FROM "ArchiveRecord" WHERE id=${record.id}`;
      if(!saved?.workflowSnapshot)throw new Error('缺少归档核对快照，请退回重新送审');
      await assertClosureReady(tx,record.matterId,saved.workflowSnapshot.fingerprint,{supplement:Boolean(saved.supplementOfId)});supplementOfId=saved.supplementOfId;
    }
    await approvalAudit(tx, session.user.id, "ARCHIVE_APPROVE", data.archiveId, {
      note: data.note?.trim() ?? "",
      attachmentIds: snapshot.documentIds,
      policyFileId: snapshot.policy.sourceFileId,
      policyVersion: snapshot.policy.version,
      verificationIds: requiredIds,
      exceptionApproved: data.exceptionApproved
    });
    await tx.archiveRecord.update({
      where: { id: record.id, status: "PENDING_REVIEW" },
      data: {
        status: "APPROVED",
        reviewedById: session.user.id,
        reviewedAt: now,
        reviewNote: data.note?.trim() || null
      }
    });
    if(!supplementOfId)await tx.matter.update({
      where: { id: record.matterId },
      data: { status: "ARCHIVED", archivedAt: now, closedAt: record.completedAt }
    });
    await recordTimelineEvent(tx, {
        matterId: record.matterId,
        eventType: "MATTER_ARCHIVED",
        title: `案件已归档（${record.archiveNo}）`,
        content: data.note?.trim() ? `审批意见：${data.note.trim()}` : "审批人已逐项核验并通过",
        occurredAt: now
      });
    if(await closureReady(tx)){const frozen=await buildArchiveManifest(tx,record.id);await tx.$executeRaw`UPDATE "ArchiveRecord" SET "frozenManifest"=${JSON.stringify(frozen)}::jsonb WHERE id=${record.id}`;}
  });

  // v0.18: 通知申请人
  if (record.archivedById && record.archivedById !== session.user.id) {
    const matter = await prisma.matter.findUnique({
      where: { id: record.matterId },
      select: { title: true, internalCode: true }
    });
    await createNotification({
      userId: record.archivedById,
      type: "ARCHIVE_APPROVED",
      priority: "NORMAL",
      title: `归档申请已通过（${record.archiveNo}）`,
      content: `案件 ${matter?.internalCode ?? record.matterId}·${matter?.title ?? ""} 的归档申请已获管理员批准。`,
      href: matterHref({ id: record.matterId, internalCode: matter?.internalCode ?? null }),
      refType: "ArchiveRecord",
      refId: record.id
    });
  }

  await audit({
    userId: session.user.id,
    action: "ARCHIVE_APPROVE",
    targetType: "ArchiveRecord",
    targetId: record.id,
    detail: { matterId: record.matterId, archiveNo: record.archiveNo }
  });

  await revalidateMatter(record.matterId);
  revalidatePath("/matters");
  revalidatePath("/archive");
  revalidatePath("/approvals");
  return { ok: true };
}

/**
 * v0.16: 管理员驳回归档申请
 */
export async function rejectArchiveRecord(input: { archiveId: string; note: string }) {
  const session = await requireSession("approval");
  if (!input.note.trim()) throw new Error("请填写驳回原因");

  const record = await prisma.archiveRecord.findUnique({
    where: { id: input.archiveId },
    select: {
      id: true,
      matterId: true,
      status: true,
      archiveNo: true,
      coverDocId: true,
      catalogDocId: true,
      checklistJson: true,
      archivedById: true
    }
  });
  if (!record) throw new Error("归档记录不存在");
  if (record.status !== "PENDING_REVIEW") throw new Error("此归档申请已审批");

  await approvalTransaction(async tx => {
    await assertApprovalItem(session.user.id, "ARCHIVE_APPROVE", input.archiveId, tx);
  await tx.archiveRecord.update({
    where: { id: record.id, status: "PENDING_REVIEW" },
    data: {
      status: "REJECTED",
      reviewedById: session.user.id,
      reviewedAt: new Date(),
      reviewNote: input.note.trim()
    }
  });
    const snapshot = parseArchiveSnapshot(record.checklistJson);
    await approvalAudit(tx, session.user.id, "ARCHIVE_REJECT", input.archiveId, {
      note: input.note.trim(),
      attachmentIds: snapshot?.documentIds ?? [record.coverDocId, record.catalogDocId].filter((id): id is string => !!id),
      legacyMaterialSnapshot: !snapshot
    });
  });

  // v0.18: 通知申请人
  if (record.archivedById && record.archivedById !== session.user.id) {
    const matter = await prisma.matter.findUnique({
      where: { id: record.matterId },
      select: { title: true, internalCode: true }
    });
    await createNotification({
      userId: record.archivedById,
      type: "ARCHIVE_REJECTED",
      priority: "HIGH",
      title: `归档申请被驳回（${record.archiveNo}）`,
      content: `案件 ${matter?.internalCode ?? record.matterId}·${matter?.title ?? ""} 的归档申请被驳回。原因：${input.note.trim()}`,
      href: matterHref({ id: record.matterId, internalCode: matter?.internalCode ?? null }),
      refType: "ArchiveRecord",
      refId: record.id
    });
  }


  await revalidateMatter(record.matterId);
  revalidatePath("/archive");
  revalidatePath("/approvals");
  return { ok: true };
}

/**
 * 获取案件的归档准备数据：当前 checklist 模板 + 已有 ArchiveRecord（若有）
 */
export async function getArchivePrepData(matterId: string) {
  const session = await requireSession("archive.submit");
  await assertCanLeadMatter(session.user.id, matterId, "仅案件主办/协办可以准备归档");
  const matter = await prisma.matter.findUnique({
    where: { id: matterId },
    select: {
      id: true,
      title: true,
      internalCode: true,
      category: true,
      status: true,
      closedAt: true,
      archivedAt: true,
      archiveRecords: {
        orderBy: { archivedAt: "desc" },
        take: 1,
        select: {
          archiveNo: true,
          summary: true,
          judgmentSummary: true,
          closedReason: true,
          completedAt: true,
          checklistJson: true,
          missingItems: true,
          coverDocId: true,
          catalogDocId: true,
          archivedBy: true,
          archivedAt: true
        }
      }
    }
  });
  if (!matter) throw new Error("案件不存在");

  const checklist = checklistForCategory(matter.category);

  // v0.11: 取最近一次结案事件的 content 作为预填小结
  const lastCloseEvent = await prisma.timelineEvent.findFirst({
    where: { matterId, eventType: "MATTER_CLOSED" },
    orderBy: { occurredAt: "desc" },
    select: { content: true }
  });

  const [availableDocuments, policy] = await Promise.all([
    prisma.document.findMany({
      where: {
        matterId,
        deletedAt: null,
        NOT: [{ tags: { has: "卷宗封皮" } }, { tags: { has: "卷宗目录" } }]
      },
      select: {
        id: true,
        name: true,
        category: true,
        mimeType: true,
        size: true,
        archiveChecklistItemId: true,
        folder: { select: { name: true } },
        createdAt: true
      },
      orderBy: [{ folder: { orderIndex: "asc" } }, { createdAt: "asc" }]
    }),
    getArchivePolicy()
  ]);

  // 兼容已有一对一关联，作为新材料选择器的预选值；正式送审仍以本次快照为准。
  const linkedDocs = availableDocuments.filter((doc) => !!doc.archiveChecklistItemId);

  // itemId → 关联材料列表（保留全部，UI 展示首条 + 余数）
  const docsByItem: Record<string, { id: string; name: string }[]> = {};
  for (const d of linkedDocs) {
    const key = d.archiveChecklistItemId!;
    (docsByItem[key] ??= []).push({ id: d.id, name: d.name });
  }

  return {
    matter,
    checklist,
    policy,
    existingSummary: lastCloseEvent?.content ?? null,
    docsByItem,
    availableDocuments: availableDocuments.map((doc) => ({
      id: doc.id,
      name: doc.name,
      category: doc.category,
      mimeType: doc.mimeType,
      size: doc.size,
      folderName: doc.folder?.name ?? null
    }))
  };
}

/**
 * 已归档案件列表（/archive 总览页）—— 仅 status=APPROVED
 */
export async function listArchivedMatters() {
  const session = await requireSession("archive.read");
  const rows = await prisma.archiveRecord.findMany({
    where: {
      status: "APPROVED",
      matter: { deletedAt: null, ...matterReadVisibilityFilter(session.user.id, session.user.role, session.user.rolePermissions) }
    },
    orderBy: { archivedAt: "desc" },
    take: 200,
    select: {
      id: true,
      archiveNo: true,
      summary: true,
      closedReason: true,
      completedAt: true,
      archivedAt: true,
      archivedBy: true,
      archivedById: true,
      missingItems: true,
      checklistJson: true,
      matter: {
        select: {
          id: true,
          title: true,
          internalCode: true,
          firmCaseNo: true,
          category: true,
          primaryClient: { select: { name: true } }
        }
      }
    }
  });
  return rows.map((row) => ({
    ...row,
    materialSnapshotVerified: !!parseArchiveSnapshot(row.checklistJson),
    checklistJson: undefined
  }));
}

/**
 * v0.18: 律师端查询自己的已驳回归档申请
 * 用于"我的已驳回归档"入口或案件详情页 banner
 */
export async function listRejectedArchiveRecords() {
  const session = await requireSession("archive.read");
  return prisma.archiveRecord.findMany({
    where: {
      archivedById: session.user.id,
      status: "REJECTED"
    },
    orderBy: { archivedAt: "desc" },
    take: 100,
    select: {
      id: true,
      archiveNo: true,
      matterId: true,
      summary: true,
      reviewedAt: true,
      reviewNote: true,
      matter: {
        select: {
          id: true,
          title: true,
          internalCode: true,
          status: true,
          archivedAt: true
        }
      }
    }
  });
}

/**
 * v0.18: 获取案件最新一条 ArchiveRecord（无论状态）
 * 案件详情页展示"归档中/已驳回"状态 banner 用
 */
export async function getLatestArchiveRecord(matterId: string) {
  await requireSession("archive.read");
  return prisma.archiveRecord.findFirst({
    where: { matterId },
    orderBy: { archivedAt: "desc" },
    select: {
      id: true,
      archiveNo: true,
      status: true,
      archivedAt: true,
      reviewedAt: true,
      reviewNote: true,
      archivedBy: true,
      missingItems: true
    }
  });
}

/**
 * v0.20: 批量审批 —— 通过
 *
 * 单条独立处理（不强求原子），逐条复用 approveArchiveRecord 的事务。
 * 返回 { succeeded, failed }，failed 含失败原因，前端展示部分失败的情况。
 */
export async function batchApproveArchiveRecords(input: {
  archiveIds: string[];
  note?: string;
}): Promise<{
  succeeded: string[];
  failed: { id: string; error: string }[];
}> {
  void input;
  throw new Error("归档申请必须逐件核对制度、材料和人工核验事项，不能批量通过");
}

/**
 * v0.20: 批量审批 —— 驳回（统一原因）
 */
export async function batchRejectArchiveRecords(input: {
  archiveIds: string[];
  note: string;
}): Promise<{
  succeeded: string[];
  failed: { id: string; error: string }[];
}> {
  const session = await requireSession("approval");
  if (!input.archiveIds.length) throw new Error("未选择任何归档申请");
  if (input.archiveIds.length > 100) throw new Error("单次批量不超过 100 条");
  if (!input.note.trim()) throw new Error("请填写驳回原因");

  const succeeded: string[] = [];
  const failed: { id: string; error: string }[] = [];
  for (const id of input.archiveIds) {
    try {
      await rejectArchiveRecord({ archiveId: id, note: input.note });
      succeeded.push(id);
    } catch (err) {
      failed.push({ id, error: err instanceof Error ? err.message : "未知错误" });
    }
  }
  await audit({
    userId: session.user.id,
    action: "ARCHIVE_BATCH_REJECT",
    targetType: "ArchiveRecord",
    targetId: input.archiveIds.join(","),
    detail: {
      total: input.archiveIds.length,
      succeeded: succeeded.length,
      failed: failed.length,
      note: input.note.trim()
    }
  });
  return { succeeded, failed };
}
