import { describe, expect, it } from "vitest";
import {
  ARCHIVE_SNAPSHOT_VERSION,
  archiveHasExceptions,
  assertArchiveApprovalReady,
  parseArchiveSnapshot,
  requiredArchiveVerificationIds
} from "@/lib/archive/snapshot";

function snapshot(status: "ATTACHED" | "MISSING" = "ATTACHED") {
  return {
    schemaVersion: ARCHIVE_SNAPSHOT_VERSION,
    policy: {
      configured: true as const,
      name: "归档制度",
      version: "2026 版",
      effectiveAt: "2026-09-01",
      sourceFileId: "cm00000000000000000000001",
      sourceFileName: "归档制度.pdf",
      sourceFileSha256: "policy-hash"
    },
    checklist: {
      kind: "LITIGATION",
      title: "诉讼案件归档清单",
      items: [{
        id: "judgment",
        label: "裁判文书",
        required: true,
        autoGenerated: false,
        status,
        note: status === "MISSING" ? "法院尚未送达" : "",
        documentIds: status === "ATTACHED" ? ["cm00000000000000000000002"] : []
      }]
    },
    manualChecks: [{ id: "archive_scope", label: "归档范围已核对", confirmed: true, note: "" }],
    documents: status === "ATTACHED" ? [{
      id: "cm00000000000000000000002",
      name: "判决书.pdf",
      category: "JUDGMENT",
      workflowStatus: "FILED",
      version: 1,
      isLatest: true,
      folderName: "裁判",
      mimeType: "application/pdf",
      size: 1024,
      sha256: "document-hash",
      checklistItemIds: ["judgment"],
      order: 1
    }] : [],
    excludedDocuments: [],
    documentIds: status === "ATTACHED" ? ["cm00000000000000000000002"] : [],
    submittedAt: "2026-09-06T08:00:00.000Z",
    previousRecordId: null
  };
}

describe("归档材料快照", () => {
  it("拒绝把旧版布尔清单当作已固定材料", () => {
    expect(parseArchiveSnapshot({ judgment: true })).toBeNull();
  });

  it("必交缺项需要例外审批", () => {
    const parsed = parseArchiveSnapshot(snapshot("MISSING"));
    expect(parsed).not.toBeNull();
    expect(archiveHasExceptions(parsed!)).toBe(true);
  });

  it("审批核验同时覆盖清单项、人工事项和每份文件", () => {
    const parsed = parseArchiveSnapshot(snapshot())!;
    expect(requiredArchiveVerificationIds(parsed)).toEqual([
      "item:judgment",
      "manual:archive_scope",
      "document:cm00000000000000000000002"
    ]);
  });

  it("未逐项核验、未明确接受例外或缺少例外意见均不能通过", () => {
    const complete = parseArchiveSnapshot(snapshot())!;
    expect(() => assertArchiveApprovalReady({ snapshot: complete, verificationIds: [], exceptionApproved: false })).toThrow("未完成审阅");

    const missing = parseArchiveSnapshot(snapshot("MISSING"))!;
    const verificationIds = requiredArchiveVerificationIds(missing);
    expect(() => assertArchiveApprovalReady({ snapshot: missing, verificationIds, exceptionApproved: false, note: "同意" })).toThrow("明确核准例外");
    expect(() => assertArchiveApprovalReady({ snapshot: missing, verificationIds, exceptionApproved: true })).toThrow("必须填写审批意见");
    expect(assertArchiveApprovalReady({ snapshot: missing, verificationIds, exceptionApproved: true, note: "法院尚未送达，按例外归档" })).toEqual(verificationIds);
  });
});
