import { z } from "zod";
import { ActionError } from "@/lib/action-error";

export const ARCHIVE_SNAPSHOT_VERSION = 2 as const;

export const archiveItemStatusSchema = z.enum([
  "ATTACHED",
  "MISSING",
  "NOT_APPLICABLE",
  "AUTO_GENERATED"
]);

export type ArchiveItemStatus = z.infer<typeof archiveItemStatusSchema>;

export const archiveDocumentSnapshotSchema = z.object({
  id: z.string().cuid(),
  name: z.string(),
  category: z.string(),
  workflowStatus: z.string(),
  version: z.number().int().positive(),
  isLatest: z.boolean(),
  folderName: z.string().nullable(),
  mimeType: z.string().nullable(),
  size: z.number().int().nonnegative(),
  sha256: z.string().min(1),
  checklistItemIds: z.array(z.string()),
  order: z.number().int().positive()
});

export const archiveItemSnapshotSchema = z.object({
  id: z.string(),
  label: z.string(),
  required: z.boolean(),
  autoGenerated: z.boolean().default(false),
  status: archiveItemStatusSchema,
  note: z.string().default(""),
  documentIds: z.array(z.string().cuid())
});

export const archiveManualCheckSchema = z.object({
  id: z.string(),
  label: z.string(),
  confirmed: z.boolean(),
  note: z.string().default("")
});

export const archiveSnapshotSchema = z.object({
  schemaVersion: z.literal(ARCHIVE_SNAPSHOT_VERSION),
  policy: z.object({
    configured: z.literal(true),
    name: z.string(),
    version: z.string(),
    effectiveAt: z.string(),
    sourceFileId: z.string().cuid(),
    sourceFileName: z.string(),
    sourceFileSha256: z.string().min(1)
  }),
  checklist: z.object({
    kind: z.string(),
    title: z.string(),
    items: z.array(archiveItemSnapshotSchema)
  }),
  manualChecks: z.array(archiveManualCheckSchema),
  documents: z.array(archiveDocumentSnapshotSchema),
  excludedDocuments: z.array(z.object({
    id: z.string().cuid(),
    name: z.string(),
    folderName: z.string().nullable(),
    size: z.number().int().nonnegative().nullable()
  })),
  documentIds: z.array(z.string().cuid()),
  submittedAt: z.string().datetime(),
  previousRecordId: z.string().cuid().nullable()
});

export type ArchiveReviewSnapshot = z.infer<typeof archiveSnapshotSchema>;
export type ArchiveDocumentSnapshot = z.infer<typeof archiveDocumentSnapshotSchema>;

export const ARCHIVE_MANUAL_CHECKS = [
  { id: "archive_scope", label: "归档范围及实际程序终点已经核对" },
  { id: "originals_handled", label: "原件退还、移交或保管去向已经核对" },
  { id: "fees_handled", label: "律师费、代收代付及票据处理情况已经核对" },
  { id: "catalog_pagination", label: "材料顺序、卷宗目录及页码状态已经核对" }
] as const;

export const ARCHIVE_DOCUMENT_STATUS_LABELS: Record<string, string> = {
  DRAFT: "草稿",
  PENDING_REVIEW: "待审核",
  APPROVED: "已审核",
  REJECTED: "已驳回",
  FILED: "已入卷"
};

export function parseArchiveSnapshot(value: unknown): ArchiveReviewSnapshot | null {
  const parsed = archiveSnapshotSchema.safeParse(value);
  return parsed.success ? parsed.data : null;
}

export function archiveSnapshotDocumentIds(value: unknown): string[] {
  return parseArchiveSnapshot(value)?.documentIds ?? [];
}

export function archiveHasExceptions(snapshot: ArchiveReviewSnapshot): boolean {
  return snapshot.checklist.items.some(
    (item) => item.required && item.status !== "ATTACHED" && item.status !== "AUTO_GENERATED"
  );
}

export function requiredArchiveVerificationIds(snapshot: ArchiveReviewSnapshot): string[] {
  return [
    ...snapshot.checklist.items
      .filter((item) => item.required || item.status !== "MISSING")
      .map((item) => `item:${item.id}`),
    ...snapshot.manualChecks.map((item) => `manual:${item.id}`),
    ...snapshot.documents.map((doc) => `document:${doc.id}`)
  ];
}

export function assertArchiveApprovalReady(input: {
  snapshot: ArchiveReviewSnapshot;
  verificationIds: string[];
  exceptionApproved: boolean;
  note?: string;
}) {
  const requiredIds = requiredArchiveVerificationIds(input.snapshot);
  const verified = new Set(input.verificationIds);
  const missing = requiredIds.filter((id) => !verified.has(id));
  if (missing.length) throw new ActionError(`仍有 ${missing.length} 项材料或核验事项未完成审阅`);
  if (archiveHasExceptions(input.snapshot) && !input.exceptionApproved) {
    throw new ActionError("该申请存在缺项或不适用项目，请明确核准例外");
  }
  if (archiveHasExceptions(input.snapshot) && !input.note?.trim()) {
    throw new ActionError("核准缺项或不适用例外时必须填写审批意见");
  }
  return requiredIds;
}
